const requireConfig = require('node:module').createRequire(__filename);

const { defineConfig } = requireConfig('oxlint');
const core = requireConfig('ultracite/oxlint/core').default;
const generatedFiles = requireConfig('./scripts/generated-files.cjs');

// Existing handwritten SDK patterns predate these preset rules.
const compatibilityRules = ['func-style', 'sort-keys'];

module.exports = defineConfig({
  extends: [core],
  categories: {
    correctness: 'off',
  },
  rules: {
    ...Object.fromEntries(compatibilityRules.map((rule) => [rule, 'off'])),
    // Preserve intentional paired null-or-undefined checks while enforcing strict
    // equality for every other comparison.
    eqeqeq: ['error', 'always', { null: 'ignore' }],
    'jsdoc/check-tag-names': ['error', { definedTags: ['jest-environment'] }],
    'no-restricted-imports': [
      'error',
      {
        patterns: [
          {
            regex: '^openai(/.*)?',
            message: 'Use a relative import, not a package import.',
          },
        ],
      },
    ],
  },
  ignorePatterns: [...core.ignorePatterns, 'dist/**', 'coverage/**', ...generatedFiles],
  overrides: [
    {
      // This example intentionally shows both mutually exclusive Next.js router
      // response styles in one place.
      files: ['examples/chat-completions/stream-to-client-next.ts'],
      rules: {
        'no-unreachable': 'off',
      },
    },
    {
      // These loops deliberately inspect one inherited key or interrupt a stream
      // to exercise cancellation; the queue-draining loop is also falsely flagged.
      files: [
        'ecosystem-tests/cli.ts',
        'src/_vendor/zod-to-json-schema/util.ts',
        'tests/internal/stream-utils.test.ts',
        'tests/lib/streaming-core.test.ts',
      ],
      rules: {
        'no-unreachable-loop': 'off',
      },
    },
    {
      // Separate pushes make the ordered response items and follow-up turn or
      // paired program fixtures explicit.
      files: ['examples/responses/manual-conversation-state.ts', 'tests/lib/ResponsesParser.test.ts'],
      rules: {
        'unicorn/prefer-single-call': 'off',
      },
    },
    {
      // Preserve the vendored module's existing named and default export topology.
      files: ['src/_vendor/zod-to-json-schema/index.ts'],
      rules: {
        'unicorn/prefer-export-from': 'off',
      },
    },
    {
      // Streaming branches retain distinct logging behavior, and schema branches
      // must preserve their mutation and annotation ordering.
      files: ['src/core/streaming.ts', 'src/lib/transform.ts'],
      rules: {
        'oxc/branches-sharing-code': 'off',
      },
    },
    {
      // parseInt intentionally reads the first dotted Node.js version component;
      // Number on the split array would produce NaN instead.
      files: ['src/internal/uploads.ts'],
      rules: {
        'unicorn/prefer-number-coercion': 'off',
      },
    },
    {
      // This mock must stay constructable because the websocket client invokes it
      // as a constructor; arrow callbacks cannot be constructors.
      files: ['tests/realtime-websocket.test.ts'],
      rules: {
        'prefer-arrow-callback': 'off',
      },
    },
    {
      // These dynamic fixtures, vendored implementations, and legacy interop
      // surfaces intentionally use any; replacing it with unknown would change
      // public assignability or runtime-adapter contracts.
      files: [
        'tests/**',
        'examples/**',
        'ecosystem-tests/**',
        'scripts/_vendor/**',
        'src/_vendor/**',
        'src/internal/utils/bytes.ts',
        'src/lib/parser.ts',
        'src/lib/ResponsesParser.ts',
        'src/lib/RunnableFunction.ts',
        'src/lib/ChatCompletionStreamingRunner.ts',
        'src/internal/provider.ts',
        'src/lib/ChatCompletionRunner.ts',
        'src/internal/to-file.ts',
        'src/core/streaming.ts',
        'src/internal/utils/path.ts',
        'src/internal/qs/types.ts',
        'src/auth/workload-identity-auth.ts',
        'src/helpers/zod.ts',
        'src/lib/AbstractChatCompletionRunner.ts',
        'src/lib/responses/ResponseStream.ts',
        'src/internal/qs/stringify.ts',
        'src/lib/ChatCompletionStream.ts',
        'src/internal/uploads.ts',
        'src/internal/qs/utils.ts',
        'src/lib/AssistantStream.ts',
        'src/lib/EventStream.ts',
        'src/lib/transform.ts',
        'src/helpers/standard-schema.ts',
        'src/internal/ws-adapter.ts',
        'src/internal/ws-adapter-node.ts',
        'src/internal/ws-adapter-browser.ts',
        'src/core/EventEmitter.ts',
        'src/helpers/audio.ts',
        'src/beta/realtime/internal-base.ts',
        'src/lib/EventEmitter.ts',
        'src/beta/realtime/websocket.ts',
        'src/internal/stream-utils.ts',
        'src/realtime/ws.ts',
        'src/realtime/internal-base.ts',
        'src/realtime/websocket.ts',
        'src/beta/realtime/ws.ts',
        'src/providers/bedrock/aws.ts',
      ],
      rules: {
        'typescript/no-explicit-any': 'off',
      },
    },
    {
      // These modules intentionally use hoisted helpers to keep public entrypoints,
      // parsers, and test fixtures readable while still enforcing variable ordering.
      files: [
        'examples/audio/audio.ts',
        'examples/chat-completions/chat-params-types.ts',
        'examples/chat-completions/function-call-diy.ts',
        'examples/chat-completions/function-call-stream-raw.ts',
        'examples/chat-completions/function-call-stream.ts',
        'examples/chat-completions/function-call.ts',
        'examples/chat-completions/tool-call-helpers.ts',
        'examples/chat-completions/tool-calls-stream.ts',
        'examples/images/picture.ts',
        'src/helpers/standard-schema.ts',
        'src/internal/decoders/line.ts',
        'src/internal/to-file.ts',
        'src/lib/AssistantStream.ts',
        'src/lib/ChatCompletionStream.ts',
        'src/lib/ResponsesParser.ts',
        'src/lib/parser.ts',
        'src/lib/responses/ResponseAccumulator.ts',
        'src/lib/responses/ResponseInputItems.ts',
        'src/lib/responses/ResponseStream.ts',
        'src/lib/transform.ts',
        'tests/benchmarks/streaming.bench.ts',
        'tests/benchmarks/structured-output-and-embeddings.bench.ts',
        'tests/lib/ResponseAccumulator.test.ts',
        'tests/lib/ResponseStream.test.ts',
        'tests/test-script.test.ts',
      ],
      rules: {
        'no-use-before-define': ['error', { functions: false }],
      },
    },
    {
      // These fixture, vendor, and state-machine files rely on deliberate
      // declaration ordering or recursive initialization that is risky to reorder.
      files: [
        'ecosystem-tests/bun/openai.test.ts',
        'ecosystem-tests/cli.ts',
        'ecosystem-tests/node-ts-cjs-auto/tests/test.ts',
        'ecosystem-tests/node-ts-cjs-web/tests/test-jsdom.ts',
        'ecosystem-tests/node-ts-cjs-web/tests/test-node.ts',
        'ecosystem-tests/node-ts-cjs/tests/test-jsdom.ts',
        'ecosystem-tests/node-ts-cjs/tests/test-node.ts',
        'ecosystem-tests/node-ts-esm-auto/tests/test.ts',
        'ecosystem-tests/node-ts-esm-web/tests/test.ts',
        'ecosystem-tests/node-ts-esm/tests/test-esnext.ts',
        'ecosystem-tests/node-ts-esm/tests/test.ts',
        'ecosystem-tests/node-ts4.5-jest28/tests/test.ts',
        'examples/chat-completions/parsing-run-tools.ts',
        'examples/chat-completions/tool-call-helpers-zod.ts',
        'examples/responses/websocket.ts',
        'src/_vendor/partial-json-parser/parser.ts',
        'src/_vendor/zod-to-json-schema/parseDef.ts',
        'src/_vendor/zod-to-json-schema/parsers/date.ts',
        'src/_vendor/zod-to-json-schema/parsers/string.ts',
        'src/_vendor/zod-to-json-schema/parsers/union.ts',
        'src/azure.ts',
        'src/core/streaming.ts',
        'src/internal/uploads.ts',
        'src/lib/EventEmitter.ts',
        'src/lib/EventStream.ts',
        'tests/buildHeaders.test.ts',
      ],
      rules: {
        'no-use-before-define': 'off',
      },
    },
    {
      // These signatures intentionally expose direct `void` for zero-argument events,
      // and the type test verifies the public `APIPromise<void>` contract.
      files: [
        'src/core/EventEmitter.ts',
        'src/lib/EventEmitter.ts',
        'src/lib/EventStream.ts',
        'tests/responses.test.ts',
      ],
      rules: {
        'typescript/no-invalid-void-type': 'off',
      },
    },
    {
      files: [
        'src/_vendor/zod-to-json-schema/index.ts',
        'src/api-promise.ts',
        'src/pagination.ts',
        'src/resource.ts',
        'src/resources.ts',
        'src/streaming.ts',
        'src/uploads.ts',
      ],
      rules: {
        'oxc/no-barrel-file': 'off',
      },
    },
    {
      // Vendored zod-to-json-schema uses `{}` for the intentionally empty schema
      // that accepts any JSON value; preserve that public type surface.
      files: [
        'src/_vendor/zod-to-json-schema/parseDef.ts',
        'src/_vendor/zod-to-json-schema/parsers/any.ts',
        'src/_vendor/zod-to-json-schema/parsers/never.ts',
        'src/_vendor/zod-to-json-schema/parsers/undefined.ts',
        'src/_vendor/zod-to-json-schema/parsers/unknown.ts',
      ],
      rules: {
        'typescript/ban-types': 'off',
        'typescript/no-empty-object-type': 'off',
      },
    },
    {
      // These SDK and test helpers intentionally use typed or Node EventEmitter APIs;
      // EventTarget would lose multi-argument events, emit chaining, or public behavior.
      files: [
        'src/beta/realtime/internal-base.ts',
        'src/core/EventEmitter.ts',
        'src/realtime/internal-base.ts',
        'tests/helpers/audio-recording.test.ts',
        'tests/internal/websocket-adapters.test.ts',
        'tests/lib/core-event-emitter.test.ts',
        'tests/lib/eventEmitter.test.ts',
        'tests/lib/responsesWebSocket.test.ts',
      ],
      rules: {
        'unicorn/prefer-event-target': 'off',
      },
    },
    {
      // These files intentionally colocate one closely related class pair.
      files: [
        'src/_vendor/partial-json-parser/parser.ts',
        'src/beta/realtime/internal-base.ts',
        'src/core/EventEmitter.ts',
        'src/core/streaming.ts',
        'src/realtime/internal-base.ts',
        'tests/internal/websocket-adapters.test.ts',
        'tests/lib/ChatCompletionRunFunctions.test.ts',
        'tests/lib/responsesWebSocket.test.ts',
      ],
      rules: {
        'max-classes-per-file': ['error', { max: 2 }],
      },
    },
    {
      // Path validation deliberately creates anonymous class-expression fixtures.
      files: ['tests/path.test.ts'],
      rules: {
        'max-classes-per-file': ['error', { ignoreExpressions: true }],
      },
    },
    {
      // Jest matcher augmentation and the public ChatCompletionStream type surface
      // intentionally rely on TypeScript declaration-merging namespaces.
      files: [
        'ecosystem-tests/node-ts-cjs-auto/tests/test.ts',
        'ecosystem-tests/node-ts-cjs-web/tests/test-jsdom.ts',
        'ecosystem-tests/node-ts-cjs-web/tests/test-node.ts',
        'ecosystem-tests/node-ts-cjs/tests/test-jsdom.ts',
        'ecosystem-tests/node-ts-cjs/tests/test-node.ts',
        'ecosystem-tests/node-ts-esm-auto/tests/test.ts',
        'ecosystem-tests/node-ts-esm-web/tests/test.ts',
        'ecosystem-tests/node-ts-esm/tests/test-esnext.ts',
        'ecosystem-tests/node-ts-esm/tests/test.ts',
        'ecosystem-tests/node-ts4.5-jest28/tests/test.ts',
        'src/lib/ChatCompletionStream.ts',
      ],
      rules: {
        'typescript/no-namespace': 'off',
      },
    },
    {
      // Schema normalization intentionally deletes dynamic keys in place, and these
      // tests exercise deletion/restoration behavior directly.
      files: [
        'src/lib/transform.ts',
        'tests/internal/detect-platform.test.ts',
        'tests/internal/utils.test.ts',
        'tests/lib/bedrock-provider.test.ts',
      ],
      rules: {
        'typescript/no-dynamic-delete': 'off',
      },
    },
    {
      // These last-item reads intentionally stay compatible with the repository's
      // ES2020 declaration library, which does not include Array.prototype.at.
      files: [
        'scripts/check-node-version-policy.ts',
        'src/_vendor/partial-json-parser/parser.ts',
        'src/lib/AbstractChatCompletionRunner.ts',
        'src/lib/ChatCompletionStream.ts',
        'tests/_vendor/partial-json-parser/partial-json-parsing.test.ts',
        'tests/lib/ChatCompletionRunFunctions.test.ts',
        'tests/realtime-websocket.test.ts',
      ],
      rules: {
        'unicorn/prefer-at': 'off',
      },
    },
    {
      // These switches intentionally enumerate schema, event, or test fixture
      // variants; preserving their no-op behavior for unknown variants is safer.
      files: [
        'src/_vendor/zod-to-json-schema/parseDef.ts',
        'src/_vendor/zod-to-json-schema/parsers/bigint.ts',
        'src/_vendor/zod-to-json-schema/parsers/date.ts',
        'src/_vendor/zod-to-json-schema/parsers/number.ts',
        'src/_vendor/zod-to-json-schema/parsers/string.ts',
        'src/_vendor/zod-to-json-schema/parsers/union.ts',
        'src/lib/AssistantStream.ts',
        'tests/lib/AssistantStream.test.ts',
        'tests/live/bedrock.live.test.ts',
      ],
      rules: {
        'default-case': 'off',
      },
    },
    {
      // These promise callbacks are intentional entrypoint, memoization, deferred
      // execution, or Node stream callback boundaries whose timing must stay stable.
      files: [
        'ecosystem-tests/cli.ts',
        'examples/azure/assistants.ts',
        'examples/azure/chat.ts',
        'examples/azure/responses.ts',
        'examples/fine-tuning/fine-tuning.ts',
        'examples/images/image-stream.ts',
        'examples/images/picture.ts',
        'examples/responses/manual-conversation-state.ts',
        'examples/responses/websocket.ts',
        'scripts/_vendor/tsc-multi/src/worker/entry.ts',
        'src/auth/subject-token-providers.ts',
        'src/helpers/audio.ts',
        'src/lib/EventStream.ts',
        'tests/helpers/audio-recording.test.ts',
        'tests/helpers/audio.test.ts',
      ],
      rules: {
        'promise/prefer-await-to-callbacks': 'off',
      },
    },
    {
      // Function-tool fixtures intentionally give callbacks semantic names such as
      // getWeather while assigning them to the protocol function field.
      files: ['tests/lib/ChatCompletionRunFunctions.test.ts'],
      rules: {
        'func-name-matching': 'off',
      },
    },
    {
      // These chains intentionally preserve fire-and-forget entrypoints, deferred
      // execution, cancellation consumption, and memoized promise lifetimes.
      files: [
        'ecosystem-tests/cli.ts',
        'examples/audio/speech-to-text.ts',
        'examples/audio/text-to-speech.ts',
        'examples/azure/assistants.ts',
        'examples/azure/chat.ts',
        'examples/azure/responses.ts',
        'examples/bedrock/responses.ts',
        'examples/chat-completions/stream-to-client-browser.ts',
        'examples/chat-completions/stream-to-client-express.ts',
        'examples/chat-completions/stream-to-client-raw.ts',
        'examples/client/raw-response.ts',
        'examples/fine-tuning/fine-tuning.ts',
        'examples/images/image-stream.ts',
        'examples/images/picture.ts',
        'examples/responses/manual-conversation-state.ts',
        'examples/responses/structured-outputs.ts',
        'examples/responses/websocket.ts',
        'scripts/_vendor/tsc-multi/src/worker/entry.ts',
        'src/auth/subject-token-providers.ts',
        'src/auth/workload-identity-auth.ts',
        'src/core/streaming.ts',
        'src/helpers/standard-schema.ts',
        'src/lib/EventStream.ts',
      ],
      rules: {
        'promise/prefer-await-to-then': 'off',
      },
    },
    {
      // These TypeScript files intentionally stay compatible with the ES2020
      // declaration library, which does not include String.prototype.replaceAll.
      files: [
        'scripts/_vendor/tsc-multi/src/worker/worker.ts',
        'src/helpers/zod.ts',
        'src/internal/qs/formats.ts',
        'src/internal/qs/stringify.ts',
        'src/internal/qs/utils.ts',
        'src/internal/uploads.ts',
        'src/internal/utils/path.ts',
        'src/lib/transform.ts',
        'src/realtime/internal-base.ts',
        'tests/helpers/zod.test.ts',
        'tests/path.test.ts',
        'tests/qs/stringify.test.ts',
        'tests/utils/mock-snapshots.ts',
      ],
      rules: {
        'unicorn/prefer-string-replace-all': 'off',
      },
    },
    {
      // These executors intentionally use concise callback bodies; their returned
      // values are ignored by Promise and changing the bodies would be behavior-neutral churn.
      files: [
        'ecosystem-tests/browser-direct-import/public/index.js',
        'ecosystem-tests/browser-direct-import/src/test.ts',
        'ecosystem-tests/cli.ts',
        'ecosystem-tests/proxy.ts',
        'ecosystem-tests/ts-browser-webpack/src/index.ts',
        'ecosystem-tests/ts-browser-webpack/src/test.ts',
        'examples/chat-completions/tool-calls-stream.ts',
        'examples/fine-tuning/fine-tuning.ts',
        'src/lib/AssistantStream.ts',
        'src/lib/ChatCompletionStream.ts',
        'src/lib/ChatCompletionStreamingRunner.ts',
        'src/lib/responses/ResponseStream.ts',
        'tests/auth/workload-identity-auth.test.ts',
        'tests/helpers/standard-schema.test.ts',
        'tests/lib/azure.test.ts',
        'tests/lib/ChatCompletionRunFunctions.test.ts',
        'tests/lib/responsesWebSocket.test.ts',
        'tests/lib/workload-identity.test.ts',
      ],
      rules: {
        'no-promise-executor-return': 'off',
      },
    },
    {
      // These sites intentionally preserve explicit undefined values for resolver
      // arity, protocol snapshots, and tests that cover undefined behavior.
      files: [
        'scripts/_vendor/tsc-multi/src/worker/worker.ts',
        'src/_vendor/zod-to-json-schema/parseDef.ts',
        'src/_vendor/zod-to-json-schema/parsers/string.ts',
        'src/_vendor/zod-to-json-schema/zodToJsonSchema.ts',
        'src/core/streaming.ts',
        'src/helpers/standard-schema.ts',
        'src/lib/AssistantStream.ts',
        'src/lib/ChatCompletionStream.ts',
        'src/lib/ChatCompletionStreamingRunner.ts',
        'src/lib/EventStream.ts',
        'src/lib/responses/ResponseStream.ts',
        'tests/internal/stream-utils.test.ts',
        'tests/internal/utils.test.ts',
        'tests/lib/AssistantStream.test.ts',
        'tests/lib/ChatCompletionRunFunctions.test.ts',
        'tests/lib/ResponsesParser.behavior.test.ts',
        'tests/lib/chatCompletionUtils.test.ts',
        'tests/lib/core-error.test.ts',
        'tests/lib/streaming-core.test.ts',
        'tests/qs/stringify.test.ts',
        'tests/sdk-behavior.test.ts',
      ],
      rules: {
        'unicorn/no-useless-undefined': 'off',
      },
    },
    {
      // These constructors intentionally create deferred, timer, stream, and test
      // promises; Promise.withResolvers would change the supported runtime surface.
      files: [
        'ecosystem-tests/browser-direct-import/public/index.js',
        'ecosystem-tests/browser-direct-import/src/test.ts',
        'ecosystem-tests/cli.ts',
        'ecosystem-tests/proxy.ts',
        'ecosystem-tests/ts-browser-webpack/src/index.ts',
        'ecosystem-tests/ts-browser-webpack/src/test.ts',
        'examples/audio/audio.ts',
        'examples/chat-completions/tool-calls-stream.ts',
        'examples/fine-tuning/fine-tuning.ts',
        'examples/responses/websocket.ts',
        'scripts/_vendor/tsc-multi/src/build.ts',
        'src/core/EventEmitter.ts',
        'src/helpers/audio.ts',
        'src/lib/AssistantStream.ts',
        'src/lib/ChatCompletionStream.ts',
        'src/lib/ChatCompletionStreamingRunner.ts',
        'src/lib/EventEmitter.ts',
        'src/lib/EventStream.ts',
        'src/lib/responses/ResponseStream.ts',
        'tests/auth/workload-identity-auth.test.ts',
        'tests/helpers/standard-schema.test.ts',
        'tests/lib/azure.test.ts',
        'tests/lib/ChatCompletionRunFunctions.test.ts',
        'tests/lib/ResponseStream.test.ts',
        'tests/lib/responsesWebSocket.test.ts',
        'tests/lib/workload-identity.test.ts',
        'tests/utils/mock-fetch.ts',
      ],
      rules: {
        'promise/avoid-new': 'off',
      },
    },
    {
      // These validation and tooling regular expressions intentionally use legacy
      // positional or non-semantic groups; renaming groups can change regex consumers.
      files: [
        'scripts/_vendor/tsc-multi/src/transformer.ts',
        'scripts/_vendor/tsc-multi/src/worker/worker.ts',
        'scripts/check-node-version-policy.ts',
        'scripts/utils/check-version.cjs',
        'scripts/utils/fix-index-exports.cjs',
        'scripts/utils/make-dist-package-json.cjs',
        'scripts/utils/postprocess-files.cjs',
        'src/_vendor/zod-to-json-schema/parsers/string.ts',
        'src/providers/bedrock/aws.ts',
        'vitest.config.mts',
      ],
      rules: {
        'prefer-named-capture-group': 'off',
      },
    },
    {
      // These ignores intentionally span multiple TypeScript versions, runtimes,
      // and fixture environments where ts-expect-error can become spuriously unused.
      files: [
        'ecosystem-tests/bun/openai.test.ts',
        'ecosystem-tests/cloudflare-worker/src/uploadWebApiTestCases.ts',
        'ecosystem-tests/node-ts-cjs-auto/tests/test.ts',
        'ecosystem-tests/node-ts-cjs-web/tests/test-node.ts',
        'ecosystem-tests/node-ts-cjs/tests/test-node.ts',
        'ecosystem-tests/node-ts-esm-auto/tests/test.ts',
        'ecosystem-tests/node-ts-esm-web/tests/test.ts',
        'ecosystem-tests/node-ts-esm/tests/test.ts',
        'ecosystem-tests/node-ts4.5-jest28/tests/test.ts',
        'ecosystem-tests/ts-browser-webpack/src/index.ts',
        'ecosystem-tests/vercel-edge/src/uploadWebApiTestCases.ts',
        'examples/audio/audio.ts',
        'examples/chat-completions/stream-to-client-browser.ts',
        'examples/chat-completions/stream-to-client-next.ts',
        'examples/chat-completions/tool-calls-stream.ts',
        'src/beta/realtime/internal-base.ts',
        'src/beta/realtime/websocket.ts',
        'src/internal/qs/stringify.ts',
        'src/internal/qs/utils.ts',
        'src/lib/EventStream.ts',
        'src/realtime/internal-base.ts',
        'src/realtime/websocket.ts',
        'tests/lib/ChatCompletionRunFunctions.test.ts',
        'tests/qs/stringify.test.ts',
        'tests/uploads.test.ts',
        'tests/utils/mock-fetch.ts',
      ],
      rules: {
        'typescript/prefer-ts-expect-error': 'off',
      },
    },
    {
      // These public, overload, and declaration-merging surfaces intentionally use
      // method signatures; property-function rewrites can change variance or overloads.
      files: [
        'ecosystem-tests/cloudflare-worker/src/uploadWebApiTestCases.ts',
        'ecosystem-tests/node-ts-cjs-auto/tests/test.ts',
        'ecosystem-tests/node-ts-cjs-web/tests/test-jsdom.ts',
        'ecosystem-tests/node-ts-cjs-web/tests/test-node.ts',
        'ecosystem-tests/node-ts-cjs/tests/test-jsdom.ts',
        'ecosystem-tests/node-ts-cjs/tests/test-node.ts',
        'ecosystem-tests/node-ts-esm-auto/tests/test.ts',
        'ecosystem-tests/node-ts-esm-web/tests/test.ts',
        'ecosystem-tests/node-ts-esm/tests/test-esnext.ts',
        'ecosystem-tests/node-ts-esm/tests/test.ts',
        'ecosystem-tests/node-ts4.5-jest28/tests/test.ts',
        'ecosystem-tests/vercel-edge/src/uploadWebApiTestCases.ts',
        'examples/responses/websocket.ts',
        'scripts/_vendor/tsc-multi/src/debug.ts',
        'scripts/_vendor/tsc-multi/src/transformer.ts',
        'src/internal/bedrock.ts',
        'src/internal/provider.ts',
        'src/internal/to-file.ts',
        'src/internal/uploads.ts',
        'src/internal/ws-adapter-browser.ts',
        'src/internal/ws-adapter.ts',
        'src/lib/AbstractChatCompletionRunner.ts',
        'src/lib/ResponsesParser.ts',
        'src/lib/parser.ts',
        'tsconfig.dist-src.d.ts',
      ],
      rules: {
        'typescript/method-signature-style': 'off',
      },
    },
    {
      // These parser, encoding, and benchmark paths intentionally use bit masks
      // and shifts; arithmetic rewrites would change low-level behavior.
      files: [
        'src/_vendor/partial-json-parser/parser.ts',
        'src/internal/qs/utils.ts',
        'tests/benchmarks/streaming.bench.ts',
      ],
      rules: {
        'no-bitwise': 'off',
      },
    },
    {
      // These checks intentionally use JavaScript's paired null-or-undefined
      // semantics; expanding them would duplicate expressions and risk evaluation changes.
      files: [
        'ecosystem-tests/browser-direct-import/src/test.ts',
        'ecosystem-tests/ts-browser-webpack/src/test.ts',
        'scripts/_vendor/tsc-multi/src/build.ts',
        'src/core/streaming.ts',
        'src/internal/bedrock.ts',
        'src/internal/decoders/line.ts',
        'src/internal/to-file.ts',
        'src/internal/uploads.ts',
        'src/internal/utils/path.ts',
        'src/lib/AbstractChatCompletionRunner.ts',
        'src/lib/AssistantStream.ts',
        'src/lib/ChatCompletionStream.ts',
        'src/lib/ResponsesParser.ts',
        'src/lib/chatCompletionUtils.ts',
        'src/lib/responses/ResponseAccumulator.ts',
        'src/lib/responses/ResponseStream.ts',
      ],
      rules: {
        'no-eq-null': 'off',
      },
    },
    {
      // These nested helpers intentionally stay close to their fixture, test, or
      // state-machine call sites; hoisting them would create collisions and reduce locality.
      files: [
        'ecosystem-tests/browser-direct-import/src/test.ts',
        'ecosystem-tests/cloudflare-worker/src/worker.ts',
        'ecosystem-tests/ts-browser-webpack/src/test.ts',
        'examples/chat-completions/function-call-stream-raw.ts',
        'examples/chat-completions/function-call-stream.ts',
        'examples/chat-completions/tool-calls-stream.ts',
        'scripts/_vendor/tsc-multi/src/report.ts',
        'scripts/check-node-version-policy.ts',
        'src/lib/EventStream.ts',
        'tests/buildHeaders.test.ts',
        'tests/form.test.ts',
        'tests/helpers/standard-schema.test.ts',
        'tests/internal/uploads-branches.test.ts',
        'tests/internal/stream-utils.test.ts',
        'tests/lib/azure.test.ts',
        'tests/lib/ChatCompletionRunFunctions.test.ts',
        'tests/lib/responsesWebSocket.test.ts',
        'tests/lib/streaming-core.test.ts',
        'tests/lib/transform.test.ts',
        'tests/lib/workload-identity.test.ts',
        'tests/qs/stringify.test.ts',
        'tests/streaming.test.ts',
        'tests/test-script.test.ts',
      ],
      rules: {
        'unicorn/consistent-function-scoping': 'off',
      },
    },
    {
      // These loops intentionally serialize streaming, retries, polling, cleanup,
      // and ordered tool-call behavior; parallelizing them would change semantics.
      files: [
        'ecosystem-tests/browser-direct-import/public/index.js',
        'ecosystem-tests/browser-direct-import/src/test.ts',
        'ecosystem-tests/bun/openai.test.ts',
        'ecosystem-tests/cli.ts',
        'ecosystem-tests/cloudflare-worker/src/uploadWebApiTestCases.ts',
        'ecosystem-tests/cloudflare-worker/src/worker.ts',
        'ecosystem-tests/deno/main_test.ts',
        'ecosystem-tests/node-ts-cjs-web/tests/test-jsdom.ts',
        'ecosystem-tests/node-ts-cjs-web/tests/test-node.ts',
        'ecosystem-tests/node-ts-esm-web/tests/test.ts',
        'ecosystem-tests/ts-browser-webpack/src/index.ts',
        'ecosystem-tests/ts-browser-webpack/src/test.ts',
        'ecosystem-tests/vercel-edge/src/pages/api/edge-test.ts',
        'ecosystem-tests/vercel-edge/src/pages/api/node-test.ts',
        'ecosystem-tests/vercel-edge/src/uploadWebApiTestCases.ts',
        'examples/chat-completions/function-call-diy.ts',
        'examples/chat-completions/function-call-stream-raw.ts',
        'examples/chat-completions/function-call-stream.ts',
        'examples/chat-completions/function-call.ts',
        'examples/chat-completions/tool-calls-stream.ts',
        'examples/fine-tuning/fine-tuning.ts',
        'examples/responses/websocket.ts',
        'src/core/streaming.ts',
        'src/lib/AbstractChatCompletionRunner.ts',
        'tests/lib/responsesWebSocket.test.ts',
      ],
      rules: {
        'no-await-in-loop': 'off',
      },
    },
    {
      // These fixture, type-test, and callback-shape files intentionally keep
      // sentinels or parameters whose presence verifies compatibility behavior.
      files: [
        'ecosystem-tests/browser-direct-import/public/index.js',
        'ecosystem-tests/bun/openai.test.ts',
        'ecosystem-tests/cloudflare-worker/src/uploadWebApiTestCases.ts',
        'ecosystem-tests/cloudflare-worker/src/worker.ts',
        'ecosystem-tests/node-js/test.js',
        'ecosystem-tests/node-ts-cjs-auto/moduleResolution/node/type-tests.ts',
        'ecosystem-tests/node-ts-cjs-auto/moduleResolution/nodenext/type-tests.ts',
        'ecosystem-tests/node-ts-cjs-auto/tests/test.ts',
        'ecosystem-tests/node-ts-cjs-web/tests/test-jsdom.ts',
        'ecosystem-tests/node-ts-cjs-web/tests/test-node.ts',
        'ecosystem-tests/node-ts-cjs-web/types-test.ts',
        'ecosystem-tests/node-ts-cjs/tests/test-jsdom.ts',
        'ecosystem-tests/node-ts-cjs/tests/test-node.ts',
        'ecosystem-tests/node-ts-esm-auto/esnext-type-tests.ts',
        'ecosystem-tests/node-ts-esm-auto/tests/test.ts',
        'ecosystem-tests/node-ts-esm-web/tests/test.ts',
        'ecosystem-tests/node-ts-esm-web/types-test.ts',
        'ecosystem-tests/node-ts-esm/tests/test-esnext.ts',
        'ecosystem-tests/node-ts-esm/tests/test.ts',
        'ecosystem-tests/node-ts4.5-jest28/tests/test.ts',
        'ecosystem-tests/proxy.ts',
        'ecosystem-tests/ts-browser-webpack/src/index.ts',
        'ecosystem-tests/vercel-edge/src/pages/api/edge-test.ts',
        'ecosystem-tests/vercel-edge/src/pages/api/query-params.ts',
        'ecosystem-tests/vercel-edge/src/pages/api/response.ts',
        'ecosystem-tests/vercel-edge/src/pages/api/streaming.ts',
        'ecosystem-tests/vercel-edge/src/pages/api/transcribe.ts',
        'ecosystem-tests/vercel-edge/src/uploadWebApiTestCases.ts',
        'examples/chat-completions/chat-params-types.ts',
        'examples/chat-completions/stream-to-client-browser.ts',
        'src/_vendor/zod-to-json-schema/parsers/date.ts',
        'src/_vendor/zod-to-json-schema/parsers/intersection.ts',
        'src/_vendor/zod-to-json-schema/parsers/string.ts',
        'src/core/EventEmitter.ts',
        'src/helpers/audio.ts',
        'src/lib/AbstractChatCompletionRunner.ts',
        'src/lib/ChatCompletionStream.ts',
        'src/lib/ResponsesParser.ts',
        'tests/lib/azure.test.ts',
        'tests/lib/workload-identity.test.ts',
        'tests/responsesItems.test.ts',
        'tests/streaming/assistants/assistant.test.ts',
        'tests/utils/mock-fetch.ts',
        'tests/ws.test.ts',
      ],
      rules: {
        'no-unused-vars': 'off',
      },
    },
    {
      // These parser indexes, retry counters, and fixture counters intentionally
      // rely on prefix/postfix old-vs-new value semantics.
      files: [
        'ecosystem-tests/cli.ts',
        'scripts/_vendor/tsc-multi/src/build.ts',
        'scripts/lint-generated.cjs',
        'src/_vendor/partial-json-parser/parser.ts',
        'src/_vendor/zod-to-json-schema/parseDef.ts',
        'src/_vendor/zod-to-json-schema/parsers/string.ts',
        'src/_vendor/zod-to-json-schema/zodToJsonSchema.ts',
        'src/azure.ts',
        'src/helpers/standard-schema.ts',
        'src/internal/decoders/line.ts',
        'src/internal/qs/utils.ts',
        'src/internal/ws.ts',
        'src/lib/AbstractChatCompletionRunner.ts',
        'src/lib/transform.ts',
        'tests/_vendor/partial-json-parser/partial-json-parsing.test.ts',
        'tests/auth/workload-identity-auth.test.ts',
        'tests/benchmarks/streaming.bench.ts',
        'tests/generated-resource-helpers.test.ts',
        'tests/lib/azure.test.ts',
        'tests/lib/ChatCompletionRunFunctions.test.ts',
        'tests/lib/provider.test.ts',
        'tests/lib/ResponseStream.test.ts',
        'tests/lib/responsesWebSocket.test.ts',
        'tests/lib/workload-identity.test.ts',
        'tests/ws.test.ts',
      ],
      rules: {
        'no-plusplus': 'off',
      },
    },
    {
      // These directives intentionally cover cross-version, cross-runtime, and
      // vendored compatibility cases where changing the directive can break a matrix leg.
      files: [
        'ecosystem-tests/bun/openai.test.ts',
        'ecosystem-tests/cloudflare-worker/src/uploadWebApiTestCases.ts',
        'ecosystem-tests/node-ts-cjs-auto/tests/test.ts',
        'ecosystem-tests/node-ts-cjs-web/tests/test-node.ts',
        'ecosystem-tests/node-ts-cjs/tests/test-node.ts',
        'ecosystem-tests/node-ts-esm-auto/tests/test.ts',
        'ecosystem-tests/node-ts-esm-web/tests/test.ts',
        'ecosystem-tests/node-ts-esm/tests/test.ts',
        'ecosystem-tests/node-ts4.5-jest28/tests/test.ts',
        'ecosystem-tests/ts-browser-webpack/src/index.ts',
        'ecosystem-tests/vercel-edge/src/uploadWebApiTestCases.ts',
        'examples/audio/audio.ts',
        'examples/chat-completions/stream-to-client-browser.ts',
        'examples/chat-completions/stream-to-client-next.ts',
        'examples/chat-completions/tool-calls-stream.ts',
        'src/_vendor/zod-to-json-schema/parsers/string.ts',
        'src/beta/realtime/internal-base.ts',
        'src/beta/realtime/websocket.ts',
        'src/internal/qs/stringify.ts',
        'src/internal/qs/utils.ts',
        'src/lib/EventStream.ts',
        'src/realtime/internal-base.ts',
        'src/realtime/websocket.ts',
        'tests/lib/ChatCompletionRunFunctions.test.ts',
        'tests/qs/stringify.test.ts',
        'tests/uploads.test.ts',
        'tests/utils/mock-fetch.ts',
      ],
      rules: {
        'typescript/ban-ts-comment': 'off',
      },
    },
    {
      // These vendored and public type aliases intentionally preserve alias
      // semantics; converting exported aliases to interfaces changes merge behavior.
      files: [
        'ecosystem-tests/cli.ts',
        'ecosystem-tests/cloudflare-worker/src/worker.ts',
        'ecosystem-tests/ts-browser-webpack/src/index.ts',
        'ecosystem-tests/vercel-edge/src/pages/api/edge-test.ts',
        'ecosystem-tests/vercel-edge/src/pages/api/node-test.ts',
        'examples/responses/websocket.ts',
        'src/_vendor/zod-to-json-schema/**',
        'src/core/streaming.ts',
        'src/helpers/audio.ts',
        'src/helpers/standard-schema.ts',
        'src/internal/qs/types.ts',
        'src/internal/uploads.ts',
        'src/lib/AbstractChatCompletionRunner.ts',
        'src/lib/ChatCompletionStream.ts',
        'src/lib/EventStream.ts',
        'src/lib/ResponsesParser.ts',
        'src/lib/RunnableFunction.ts',
        'src/lib/parser.ts',
        'src/lib/responses/ResponseAccumulator.ts',
        'src/lib/responses/ResponseStream.ts',
        'src/lib/transform.ts',
        'src/providers/bedrock/aws.ts',
        'tests/benchmarks/streaming.bench.ts',
        'tests/helpers/standard-schema.test.ts',
        'tests/helpers/zod.test.ts',
        'tests/internal/detect-platform.test.ts',
        'tests/lib/core-event-emitter.test.ts',
        'tests/lib/eventEmitter.test.ts',
        'tests/lib/pagination.test.ts',
        'tests/realtime-websocket.test.ts',
        'tests/responsesTools.test.ts',
      ],
      rules: {
        'typescript/consistent-type-definitions': 'off',
      },
    },
    {
      // These inline comments intentionally preserve vendored context, bundler
      // annotations, release markers, or fixture explanations at the exact site.
      files: [
        'ecosystem-tests/browser-direct-import/public/index.js',
        'examples/chat-completions/parsing-run-tools.ts',
        'examples/chat-completions/parsing-stream.ts',
        'examples/chat-completions/parsing-tools-stream.ts',
        'examples/chat-completions/parsing-tools.ts',
        'examples/chat-completions/parsing.ts',
        'examples/chat-completions/tool-call-helpers-zod.ts',
        'examples/chat-completions/ui-generation.ts',
        'examples/responses/streaming-tools.ts',
        'examples/responses/structured-outputs-tools.ts',
        'examples/responses/structured-outputs.ts',
        'scripts/utils/postprocess-files.cjs',
        'src/_vendor/partial-json-parser/parser.ts',
        'src/_vendor/zod-to-json-schema/parseDef.ts',
        'src/_vendor/zod-to-json-schema/parsers/date.ts',
        'src/_vendor/zod-to-json-schema/parsers/string.ts',
        'src/_vendor/zod-to-json-schema/parsers/union.ts',
        'src/beta/realtime/websocket.ts',
        'src/beta/realtime/ws.ts',
        'src/helpers/audio.ts',
        'src/internal/decoders/line.ts',
        'src/internal/qs/stringify.ts',
        'src/internal/qs/utils.ts',
        'src/internal/stream-utils.ts',
        'src/internal/to-file.ts',
        'src/internal/uploads.ts',
        'src/internal/utils/path.ts',
        'src/internal/ws.ts',
        'src/lib/AssistantStream.ts',
        'src/lib/ChatCompletionStream.ts',
        'src/lib/ResponsesParser.ts',
        'src/lib/jsonschema.ts',
        'src/lib/parser.ts',
        'src/realtime/websocket.ts',
        'src/realtime/ws.ts',
        'src/version.ts',
        'tests/lib/azure.test.ts',
      ],
      rules: {
        'no-inline-comments': 'off',
      },
    },
    {
      // These indexed and property reads intentionally preserve existing narrowing,
      // bounds checks, and evaluation order; destructuring can change those shapes.
      files: [
        'ecosystem-tests/cli.ts',
        'examples/chat-completions/function-call-diy.ts',
        'examples/chat-completions/function-call.ts',
        'examples/chat-completions/tool-calls-stream.ts',
        'examples/chat-completions/ui-generation.ts',
        'examples/responses/stream_background.ts',
        'scripts/_vendor/tsc-multi/src/config.ts',
        'scripts/_vendor/tsc-multi/src/worker/worker.ts',
        'scripts/utils/check-version.cjs',
        'src/_vendor/partial-json-parser/parser.ts',
        'src/beta/realtime/internal-base.ts',
        'src/beta/realtime/websocket.ts',
        'src/beta/realtime/ws.ts',
        'src/helpers/standard-schema.ts',
        'src/helpers/zod.ts',
        'src/internal/bedrock.ts',
        'src/internal/qs/stringify.ts',
        'src/internal/ws.ts',
        'src/lib/AssistantStream.ts',
        'src/lib/EventStream.ts',
        'src/lib/responses/ResponseAccumulator.ts',
        'src/lib/responses/ResponseInputItems.ts',
        'src/lib/transform.ts',
        'src/providers/bedrock/aws.ts',
        'src/realtime/internal-base.ts',
        'src/realtime/websocket.ts',
        'src/realtime/ws.ts',
        'tests/generated-resource-helpers.test.ts',
        'tests/helpers/standard-schema.test.ts',
        'tests/internal/websocket-adapters.test.ts',
        'tests/lib/azure.test.ts',
        'tests/lib/bedrock.test.ts',
        'tests/lib/ChatCompletionRunFunctions.test.ts',
        'tests/lib/ChatCompletionStream.test.ts',
        'tests/lib/ResponseStream.test.ts',
        'tests/lib/responsesWebSocket.test.ts',
        'tests/lib/transform.test.ts',
        'tests/log.test.ts',
        'tests/qs/utils.test.ts',
        'tests/utils/mock-snapshots.ts',
      ],
      rules: {
        'prefer-destructuring': 'off',
      },
    },
    {
      // These mixed value/type import groups intentionally stay colocated to preserve
      // public-module grouping and avoid duplicate import declarations.
      files: [
        'src/lib/AbstractChatCompletionRunner.ts',
        'src/lib/ChatCompletionStream.ts',
        'src/lib/ResponsesParser.ts',
        'src/lib/responses/ResponseStream.ts',
        'src/providers/bedrock.ts',
        'src/providers/bedrock/aws.ts',
        'src/realtime/websocket.ts',
        'src/realtime/ws.ts',
        'tests/buildHeaders.test.ts',
        'tests/lib/ChatCompletionRunFunctions.test.ts',
      ],
      rules: {
        'import/consistent-type-specifier-style': 'off',
      },
    },
    {
      // These concatenations intentionally preserve existing coercion, parser,
      // and fixture formatting behavior; template rewrites are not uniformly equivalent.
      files: [
        'ecosystem-tests/cli.ts',
        'examples/assistants/assistant-stream.ts',
        'examples/assistants/assistants.ts',
        'examples/azure/assistants.ts',
        'examples/mtls/bun.mjs',
        'examples/mtls/deno.mjs',
        'examples/mtls/node.mjs',
        'scripts/_vendor/tsc-multi/src/transformer.ts',
        'scripts/_vendor/tsc-multi/src/worker/worker.ts',
        'scripts/utils/attw-report.cjs',
        'scripts/utils/postprocess-files.cjs',
        'src/_vendor/partial-json-parser/parser.ts',
        'src/beta/realtime/internal-base.ts',
        'src/core/streaming.ts',
        'src/internal/qs/stringify.ts',
        'src/internal/qs/utils.ts',
        'src/internal/uploads.ts',
        'src/internal/utils/path.ts',
        'src/lib/transform.ts',
        'src/realtime/internal-base.ts',
        'tests/helpers/zod.test.ts',
        'tests/lib/AssistantStream.test.ts',
        'tests/lib/EventStream.test.ts',
        'tests/lib/ResponseStream.test.ts',
        'tests/lib/transform.test.ts',
        'tests/path.test.ts',
        'tests/qs/stringify.test.ts',
        'tests/streaming/assistants/assistant.test.ts',
      ],
      rules: {
        'prefer-template': 'off',
      },
    },
    {
      // These assertions encode validated parser, stream, and fixture invariants;
      // removing them mechanically would duplicate guards or weaken narrowing.
      files: [
        'ecosystem-tests/node-ts-cjs/tests/test-node.ts',
        'ecosystem-tests/node-ts-esm-auto/tests/test.ts',
        'ecosystem-tests/node-ts4.5-jest28/tests/test.ts',
        'ecosystem-tests/proxy.ts',
        'ecosystem-tests/vercel-edge/src/uploadWebApiTestCases.ts',
        'examples/audio/audio.ts',
        'examples/azure/chat.ts',
        'examples/chat-completions/function-call-diy.ts',
        'examples/chat-completions/function-call-stream-raw.ts',
        'examples/chat-completions/function-call-stream.ts',
        'examples/chat-completions/function-call.ts',
        'examples/chat-completions/tool-call-helpers-zod.ts',
        'examples/chat-completions/tool-call-helpers.ts',
        'examples/chat-completions/tool-calls-stream.ts',
        'examples/chat-completions/ui-generation.ts',
        'examples/responses/stream_background.ts',
        'examples/responses/structured-outputs-tools.ts',
        'src/_vendor/partial-json-parser/parser.ts',
        'src/_vendor/zod-to-json-schema/parsers/nativeEnum.ts',
        'src/_vendor/zod-to-json-schema/parsers/object.ts',
        'src/_vendor/zod-to-json-schema/parsers/string.ts',
        'src/_vendor/zod-to-json-schema/parsers/union.ts',
        'src/beta/realtime/internal-base.ts',
        'src/core/streaming.ts',
        'src/helpers/audio.ts',
        'src/internal/qs/utils.ts',
        'src/internal/utils/path.ts',
        'src/internal/ws.ts',
        'src/lib/AssistantStream.ts',
        'src/lib/ChatCompletionStream.ts',
        'src/lib/EventStream.ts',
        'src/lib/responses/ResponseStream.ts',
        'src/lib/transform.ts',
        'src/providers/bedrock/aws.ts',
        'src/realtime/internal-base.ts',
        'tests/_vendor/partial-json-parser/partial-json-parsing.test.ts',
        'tests/auth/workload-identity-auth.test.ts',
        'tests/benchmarks/structured-output-and-embeddings.bench.ts',
        'tests/helpers/zod.test.ts',
        'tests/internal/uploads-branches.test.ts',
        'tests/internal/websocket-adapters.test.ts',
        'tests/lib/bedrock-provider.test.ts',
        'tests/lib/bedrock.test.ts',
        'tests/lib/ResponseAccumulator.test.ts',
        'tests/lib/ResponseInputItems.test.ts',
        'tests/lib/responsesWebSocket.test.ts',
        'tests/lib/workload-identity.test.ts',
        'tests/realtime-websocket.test.ts',
      ],
      rules: {
        'typescript/no-non-null-assertion': 'off',
      },
    },
    {
      // These are the two existing SDK/vendor cycle clusters; untangling module
      // topology would be a behavior and public-surface refactor, not lint cleanup.
      files: [
        'src/_vendor/zod-to-json-schema/**',
        'src/azure.ts',
        'src/bedrock.ts',
        'src/core/streaming.ts',
        'src/lib/AbstractChatCompletionRunner.ts',
        'src/lib/AssistantStream.ts',
        'src/lib/ChatCompletionRunner.ts',
        'src/lib/ChatCompletionStream.ts',
        'src/lib/ChatCompletionStreamingRunner.ts',
        'src/lib/ResponsesParser.ts',
        'src/lib/parser.ts',
        'src/lib/responses/ResponseAccumulator.ts',
        'src/lib/responses/ResponseStream.ts',
      ],
      rules: {
        'import/no-cycle': 'off',
      },
    },
    {
      // These existing runtime, vendor, and fixture regexes intentionally retain
      // legacy regexp semantics; adding Unicode mode can change matching or validity.
      files: [
        'ecosystem-tests/cli.ts',
        'ecosystem-tests/ts-browser-webpack/webpack.config.js',
        'examples/azure/chat.ts',
        'examples/azure/responses.ts',
        'scripts/_vendor/tsc-multi/src/transformer.ts',
        'scripts/_vendor/tsc-multi/src/worker/worker.ts',
        'scripts/check-node-version-policy.ts',
        'scripts/generated-files.cjs',
        'scripts/test-packed-package.ts',
        'scripts/utils/check-version.cjs',
        'scripts/utils/fix-index-exports.cjs',
        'scripts/utils/make-dist-package-json.cjs',
        'scripts/utils/postprocess-files.cjs',
        'src/_vendor/zod-to-json-schema/parseDef.ts',
        'src/_vendor/zod-to-json-schema/parsers/string.ts',
        'src/bedrock.ts',
        'src/helpers/zod.ts',
        'src/internal/bedrock.ts',
        'src/internal/decoders/line.ts',
        'src/internal/qs/formats.ts',
        'src/internal/qs/stringify.ts',
        'src/internal/qs/utils.ts',
        'src/internal/to-file.ts',
        'src/internal/uploads.ts',
        'src/internal/utils/path.ts',
        'src/lib/transform.ts',
        'src/providers/bedrock/aws.ts',
        'src/realtime/internal-base.ts',
        'tests/buildHeaders.test.ts',
        'tests/client-behavior.test.ts',
        'tests/form.test.ts',
        'tests/helpers/zod.test.ts',
        'tests/internal/uploads-branches.test.ts',
        'tests/internal/utils.test.ts',
        'tests/lib/azure.test.ts',
        'tests/lib/bedrock-provider.test.ts',
        'tests/lib/bedrock.test.ts',
        'tests/lib/ChatCompletionRunFunctions.test.ts',
        'tests/lib/workload-identity.test.ts',
        'tests/path.test.ts',
        'tests/qs/stringify.test.ts',
        'tests/qs/utils.test.ts',
        'tests/sdk-behavior.test.ts',
        'tests/utils/mock-snapshots.ts',
        'vitest.config.mts',
      ],
      rules: {
        'require-unicode-regexp': 'off',
      },
    },
    {
      // These async fixtures and SDK contracts intentionally preserve promise
      // return shapes, rejection timing, or iterator interfaces even without await.
      files: [
        'examples/**',
        'tests/**',
        'ecosystem-tests/ts-browser-webpack/src/index.ts',
        'scripts/_vendor/tsc-multi/src/config.ts',
        'src/azure.ts',
        'src/bedrock.ts',
        'src/core/streaming.ts',
        'src/helpers/audio.ts',
        'src/internal/bedrock.ts',
        'src/lib/AssistantStream.ts',
        'src/lib/ChatCompletionStream.ts',
        'src/lib/ChatCompletionStreamingRunner.ts',
        'src/lib/responses/ResponseStream.ts',
        'src/providers/bedrock/aws.ts',
      ],
      rules: {
        'require-await': 'off',
      },
    },
    {
      // These files intentionally exercise or provide CommonJS tooling, config,
      // fixture, and runtime-loading behavior; converting them would change loading.
      files: [
        'ecosystem-tests/cli.ts',
        'ecosystem-tests/node-js/test.js',
        'ecosystem-tests/ts-browser-webpack/webpack.config.js',
        'ecosystem-tests/vercel-edge/next.config.js',
        'examples/audio/audio.ts',
        'oxfmt.config.ts',
        'oxlint.config.ts',
        'scripts/_vendor/tsc-multi/src/build.ts',
        'scripts/_vendor/tsc-multi/src/worker/worker.ts',
        'scripts/check-node-version-policy.ts',
        'scripts/test-packed-package.ts',
        'tests/oxlint-config.test.ts',
        'tests/resource-exports.test.ts',
        'tests/uploads.test.ts',
        'vitest.config.mts',
      ],
      rules: {
        'unicorn/prefer-module': 'off',
      },
    },
    {
      // These vendored, fixture, and callback-heavy files intentionally reuse local
      // protocol names; renaming them would obscure the behavior under test.
      files: [
        'ecosystem-tests/browser-direct-import/src/test.ts',
        'ecosystem-tests/bun/openai.test.ts',
        'ecosystem-tests/cli.ts',
        'ecosystem-tests/node-ts-cjs/tests/test-node.ts',
        'ecosystem-tests/ts-browser-webpack/src/test.ts',
        'ecosystem-tests/vercel-edge/src/pages/api/edge-test.ts',
        'ecosystem-tests/vercel-edge/src/pages/api/node-test.ts',
        'examples/assistants/assistant-stream.ts',
        'examples/audio/audio.ts',
        'examples/mtls/deno.mjs',
        'scripts/_vendor/tsc-multi/src/transformer.ts',
        'src/_vendor/zod-to-json-schema/zodToJsonSchema.ts',
        'src/auth/workload-identity-auth.ts',
        'src/helpers/zod.ts',
        'src/lib/AbstractChatCompletionRunner.ts',
        'src/lib/ChatCompletionStream.ts',
        'src/lib/ResponsesParser.ts',
        'src/lib/parser.ts',
        'src/lib/responses/ResponseStream.ts',
        'tests/lib/ChatCompletionRunFunctions.test.ts',
        'tests/lib/azure.test.ts',
        'tests/realtime.test.ts',
        'tests/responses.test.ts',
        'tests/test-script.test.ts',
      ],
      rules: {
        'no-shadow': 'off',
      },
    },
    {
      // These existing catches use short or domain-specific names in vendored,
      // fixture, and adapter code; renaming them adds churn without behavior value.
      files: [
        'ecosystem-tests/cli.ts',
        'examples/azure/assistants.ts',
        'examples/azure/chat.ts',
        'examples/azure/responses.ts',
        'examples/client/errors.ts',
        'examples/fine-tuning/fine-tuning.ts',
        'scripts/_vendor/tsc-multi/src/utils.ts',
        'scripts/_vendor/tsc-multi/src/worker/entry.ts',
        'src/_vendor/partial-json-parser/parser.ts',
        'src/beta/realtime/websocket.ts',
        'src/beta/realtime/ws.ts',
        'src/core/streaming.ts',
        'src/internal/bedrock.ts',
        'src/internal/stream-utils.ts',
        'src/internal/ws.ts',
        'src/providers/bedrock/aws.ts',
        'src/realtime/websocket.ts',
        'src/realtime/ws.ts',
        'tests/path.test.ts',
        'tests/utils/mock-fetch.ts',
      ],
      rules: {
        'unicorn/catch-error-name': 'off',
      },
    },
    {
      // These legacy and public SDK paths are part of the package surface or
      // compatibility fixtures; renaming them would break imports and snapshots.
      files: [
        'ecosystem-tests/cloudflare-worker/src/uploadWebApiTestCases.ts',
        'ecosystem-tests/deno/main_test.ts',
        'ecosystem-tests/vercel-edge/src/uploadWebApiTestCases.ts',
        'examples/responses/stream_background.ts',
        'src/_vendor/zod-to-json-schema/Options.ts',
        'src/_vendor/zod-to-json-schema/Refs.ts',
        'src/_vendor/zod-to-json-schema/errorMessages.ts',
        'src/_vendor/zod-to-json-schema/parseDef.ts',
        'src/_vendor/zod-to-json-schema/parsers/nativeEnum.ts',
        'src/_vendor/zod-to-json-schema/zodToJsonSchema.ts',
        'src/core/EventEmitter.ts',
        'src/lib/AbstractChatCompletionRunner.ts',
        'src/lib/AssistantStream.ts',
        'src/lib/ChatCompletionRunner.ts',
        'src/lib/ChatCompletionStream.ts',
        'src/lib/ChatCompletionStreamingRunner.ts',
        'src/lib/EventEmitter.ts',
        'src/lib/EventStream.ts',
        'src/lib/ResponsesParser.ts',
        'src/lib/RunnableFunction.ts',
        'src/lib/Util.ts',
        'src/lib/chatCompletionUtils.ts',
        'src/lib/responses/EventTypes.ts',
        'src/lib/responses/ResponseAccumulator.ts',
        'src/lib/responses/ResponseInputItems.ts',
        'src/lib/responses/ResponseStream.ts',
        'tests/buildHeaders.test.ts',
        'tests/lib/AssistantStream.test.ts',
        'tests/lib/ChatCompletionRunFunctions.test.ts',
        'tests/lib/ChatCompletionStream.test.ts',
        'tests/lib/EventStream.test.ts',
        'tests/lib/ResponseAccumulator.events.test.ts',
        'tests/lib/ResponseAccumulator.test.ts',
        'tests/lib/ResponseInputItems.test.ts',
        'tests/lib/ResponseStream.test.ts',
        'tests/lib/ResponsesParser.behavior.test.ts',
        'tests/lib/ResponsesParser.test.ts',
        'tests/lib/Util.test.ts',
        'tests/lib/chatCompletionUtils.test.ts',
        'tests/lib/eventEmitter.test.ts',
        'tests/lib/responsesWebSocket.test.ts',
        'tests/responsesItems.test.ts',
        'tests/responsesTools.test.ts',
      ],
      rules: {
        'unicorn/filename-case': 'off',
      },
    },
    {
      // Sparse holes are the behavior under test in the query-string fixture;
      // replacing them with explicit undefined values would change coverage.
      files: ['tests/qs/stringify.test.ts'],
      rules: {
        'no-sparse-arrays': 'off',
      },
    },
    {
      // The vendored partial parser relies on substring's clamping and bound-swapping
      // behavior for malformed input, which is not equivalent to slice.
      files: ['src/_vendor/partial-json-parser/parser.ts'],
      rules: {
        'unicorn/prefer-string-slice': 'off',
      },
    },
    {
      // These established parsers and stream state machines intentionally encode
      // protocol branching in one place; splitting them would risk behavior changes.
      files: [
        'scripts/_vendor/tsc-multi/src/transformer.ts',
        'src/_vendor/partial-json-parser/parser.ts',
        'src/_vendor/zod-to-json-schema/parseDef.ts',
        'src/_vendor/zod-to-json-schema/parsers/string.ts',
        'src/_vendor/zod-to-json-schema/parsers/union.ts',
        'src/internal/qs/stringify.ts',
        'src/internal/qs/utils.ts',
        'src/lib/AbstractChatCompletionRunner.ts',
        'src/lib/AssistantStream.ts',
        'src/lib/ChatCompletionStream.ts',
        'src/lib/responses/ResponseAccumulator.ts',
        'src/lib/responses/ResponseInputItems.ts',
        'src/lib/transform.ts',
      ],
      rules: {
        complexity: 'off',
      },
    },
    {
      // These constructors, normalizers, and reducer fixtures intentionally rebind
      // parameters while resolving defaults or preserving accumulator semantics.
      files: [
        'ecosystem-tests/cli.ts',
        'examples/chat-completions/function-call-stream-raw.ts',
        'examples/chat-completions/function-call-stream.ts',
        'examples/chat-completions/tool-calls-stream.ts',
        'src/azure.ts',
        'src/bedrock.ts',
        'src/beta/realtime/internal-base.ts',
        'src/beta/realtime/websocket.ts',
        'src/beta/realtime/ws.ts',
        'src/core/streaming.ts',
        'src/internal/to-file.ts',
        'src/lib/EventStream.ts',
        'src/lib/responses/ResponseAccumulator.ts',
        'src/realtime/internal-base.ts',
        'src/realtime/websocket.ts',
        'src/realtime/ws.ts',
      ],
      rules: {
        'no-param-reassign': 'off',
      },
    },
    {
      files: ['tests/**', 'examples/**', 'ecosystem-tests/**'],
      rules: {
        'no-restricted-imports': 'off',
      },
    },
  ],
});
