const requireConfig = require('node:module').createRequire(__filename);
const { defineConfig } = requireConfig('oxlint');
const core = requireConfig('ultracite/oxlint/core').default;
const stainlessGeneratedFiles = requireConfig('./scripts/stainless-generated-files.cjs');

// Existing handwritten SDK patterns predate these preset rules.
const compatibilityRules = [
  'arrow-body-style',
  'class-methods-use-this',
  'complexity',
  'curly',
  'default-case',
  'eqeqeq',
  'func-name-matching',
  'func-names',
  'func-style',
  'guard-for-in',
  'import/consistent-type-specifier-style',
  'import/first',
  'import/newline-after-import',
  'import/no-cycle',
  'jsdoc/check-tag-names',
  'jsdoc/no-defaults',
  'jsdoc/require-param-description',
  'jsdoc/require-yields',
  'logical-assignment-operators',
  'max-classes-per-file',
  'no-await-in-loop',
  'no-bitwise',
  'no-case-declarations',
  'no-else-return',
  'no-empty',
  'no-empty-function',
  'no-eq-null',
  'no-fallthrough',
  'no-inline-comments',
  'no-inner-declarations',
  'no-lonely-if',
  'no-multi-assign',
  'no-negated-condition',
  'no-nested-ternary',
  'no-new-wrappers',
  'no-param-reassign',
  'no-plusplus',
  'no-promise-executor-return',
  'no-sequences',
  'no-shadow',
  'no-sparse-arrays',
  'no-throw-literal',
  'no-unsafe-optional-chaining',
  'no-unused-expressions',
  'no-unused-vars',
  'no-use-before-define',
  'no-useless-concat',
  'no-useless-escape',
  'no-useless-return',
  'no-var',
  'no-void',
  'no-warning-comments',
  'node/global-require',
  'object-shorthand',
  'oxc/no-accumulating-spread',
  'oxc/no-async-endpoint-handlers',
  'oxc/no-barrel-file',
  'prefer-arrow-callback',
  'prefer-destructuring',
  'prefer-named-capture-group',
  'prefer-object-has-own',
  'prefer-template',
  'promise/avoid-new',
  'promise/no-multiple-resolved',
  'promise/param-names',
  'promise/prefer-await-to-callbacks',
  'promise/prefer-await-to-then',
  'require-await',
  'require-unicode-regexp',
  'sort-keys',
  'typescript/array-type',
  'typescript/ban-ts-comment',
  'typescript/ban-types',
  'typescript/consistent-indexed-object-style',
  'typescript/consistent-type-definitions',
  'typescript/consistent-type-imports',
  'typescript/method-signature-style',
  'typescript/no-dynamic-delete',
  'typescript/no-empty-object-type',
  'typescript/no-explicit-any',
  'typescript/no-import-type-side-effects',
  'typescript/no-inferrable-types',
  'typescript/no-invalid-void-type',
  'typescript/no-namespace',
  'typescript/no-non-null-assertion',
  'typescript/no-unsafe-function-type',
  'typescript/no-wrapper-object-types',
  'typescript/parameter-properties',
  'typescript/prefer-for-of',
  'typescript/prefer-ts-expect-error',
  'typescript/unified-signatures',
  'unicorn/catch-error-name',
  'unicorn/consistent-assert',
  'unicorn/consistent-existence-index-check',
  'unicorn/consistent-function-scoping',
  'unicorn/custom-error-definition',
  'unicorn/filename-case',
  'unicorn/import-style',
  'unicorn/new-for-builtins',
  'unicorn/no-anonymous-default-export',
  'unicorn/no-array-for-each',
  'unicorn/no-array-reduce',
  'unicorn/no-array-reverse',
  'unicorn/no-array-sort',
  'unicorn/no-await-expression-member',
  'unicorn/no-console-spaces',
  'unicorn/no-hex-escape',
  'unicorn/no-lonely-if',
  'unicorn/no-negated-condition',
  'unicorn/no-nested-ternary',
  'unicorn/no-this-assignment',
  'unicorn/no-typeof-undefined',
  'unicorn/no-useless-switch-case',
  'unicorn/no-useless-undefined',
  'unicorn/numeric-separators-style',
  'unicorn/prefer-at',
  'unicorn/prefer-bigint-literals',
  'unicorn/prefer-class-fields',
  'unicorn/prefer-code-point',
  'unicorn/prefer-dom-node-append',
  'unicorn/prefer-dom-node-text-content',
  'unicorn/prefer-event-target',
  'unicorn/prefer-includes',
  'unicorn/prefer-logical-operator-over-ternary',
  'unicorn/prefer-module',
  'unicorn/prefer-native-coercion-functions',
  'unicorn/prefer-node-protocol',
  'unicorn/prefer-number-properties',
  'unicorn/prefer-object-from-entries',
  'unicorn/prefer-optional-catch-binding',
  'unicorn/prefer-query-selector',
  'unicorn/prefer-regexp-test',
  'unicorn/prefer-response-static-json',
  'unicorn/prefer-spread',
  'unicorn/prefer-string-replace-all',
  'unicorn/prefer-string-slice',
  'unicorn/prefer-ternary',
  'unicorn/prefer-type-error',
  'unicorn/require-module-specifiers',
  'unicorn/switch-case-braces',
  'unicorn/text-encoding-identifier-case',
  'vars-on-top',
  'yoda',
];

module.exports = defineConfig({
  extends: [core],
  categories: {
    correctness: 'off',
  },
  rules: {
    ...Object.fromEntries(compatibilityRules.map((rule) => [rule, 'off'])),
    'no-restricted-imports': [
      'error',
      {
        patterns: [
          {
            regex: '^openai(/.*)?',
            message: 'Use a relative import, not a package import.',
          },
        ],
      },
    ],
  },
  ignorePatterns: [...core.ignorePatterns, 'dist/**', 'coverage/**', ...stainlessGeneratedFiles],
  overrides: [
    {
      files: ['tests/**', 'examples/**', 'ecosystem-tests/**'],
      rules: {
        'no-restricted-imports': 'off',
      },
    },
  ],
});
