#!/usr/bin/env bash

set -exuo pipefail

cd "$(dirname "$0")/.."

rm -rf dist-deno; mkdir dist-deno
cp -rp src/* jsr.json dist-deno

rm dist-deno/_shims/auto/*-node.ts
for dir in dist-deno/_shims dist-deno/_shims/auto; do
  rm "${dir}"/*.{d.ts,js,mjs}
  for file in "${dir}"/*-deno.ts; do
    mv -- "$file" "${file%-deno.ts}.ts"
  done
done
for file in LICENSE CHANGELOG.md; do
  if [ -e "${file}" ]; then cp "${file}" dist-deno; fi
done
