// File generated from our OpenAPI spec by Castiron. See CONTRIBUTING.md for details.

import { APIResource } from '../../core/resource';
import * as AssistantsAPI from './assistants';
import {
  Assistant,
  AssistantCreateParams,
  AssistantDeleted,
  AssistantListParams,
  AssistantStreamEvent,
  AssistantTool,
  AssistantUpdateParams,
  Assistants,
  AssistantsPage,
  CodeInterpreterTool,
  FileSearchTool,
  FunctionTool,
  MessageStreamEvent,
  RunStepStreamEvent,
  RunStreamEvent,
  ThreadStreamEvent,
} from './assistants';
import * as RealtimeAPI from './realtime/realtime';
import {
  ConversationCreatedEvent,
  ConversationItem,
  ConversationItemContent,
  ConversationItemCreateEvent,
  ConversationItemCreatedEvent,
  ConversationItemDeleteEvent,
  ConversationItemDeletedEvent,
  ConversationItemInputAudioTranscriptionCompletedEvent,
  ConversationItemInputAudioTranscriptionDeltaEvent,
  ConversationItemInputAudioTranscriptionFailedEvent,
  ConversationItemRetrieveEvent,
  ConversationItemTruncateEvent,
  ConversationItemTruncatedEvent,
  ConversationItemWithReference,
  ErrorEvent,
  InputAudioBufferAppendEvent,
  InputAudioBufferClearEvent,
  InputAudioBufferClearedEvent,
  InputAudioBufferCommitEvent,
  InputAudioBufferCommittedEvent,
  InputAudioBufferSpeechStartedEvent,
  InputAudioBufferSpeechStoppedEvent,
  RateLimitsUpdatedEvent,
  Realtime,
  RealtimeClientEvent,
  RealtimeResponse,
  RealtimeResponseStatus,
  RealtimeResponseUsage,
  RealtimeServerEvent,
  ResponseAudioDeltaEvent,
  ResponseAudioDoneEvent,
  ResponseAudioTranscriptDeltaEvent,
  ResponseAudioTranscriptDoneEvent,
  ResponseCancelEvent,
  ResponseContentPartAddedEvent,
  ResponseContentPartDoneEvent,
  ResponseCreateEvent,
  ResponseCreatedEvent,
  ResponseDoneEvent,
  ResponseFunctionCallArgumentsDeltaEvent,
  ResponseFunctionCallArgumentsDoneEvent,
  ResponseOutputItemAddedEvent,
  ResponseOutputItemDoneEvent,
  ResponseTextDeltaEvent,
  ResponseTextDoneEvent,
  SessionCreatedEvent,
  SessionUpdateEvent,
  SessionUpdatedEvent,
  TranscriptionSessionUpdate,
  TranscriptionSessionUpdatedEvent,
} from './realtime/realtime';
import * as AgentsAPI from './agents/agents';
import {
  Agent,
  AgentCloseSubagentCallItem,
  AgentCommandExecutionItem,
  AgentContent,
  AgentCreateParams,
  AgentCreateSubagentCallItem,
  AgentDeleted,
  AgentFunctionCallItem,
  AgentFunctionCallOutput,
  AgentFunctionCallOutputParam,
  AgentFunctionCallStatus,
  AgentInterruptSubagentCallItem,
  AgentListParams,
  AgentMcpCallItem,
  AgentOutputCommandExecutionOutputDeltaEvent,
  AgentOutputItem,
  AgentOutputItemStatus,
  AgentReasoning,
  AgentReasoningItem,
  AgentReasoningParam,
  AgentResumeSubagentCallItem,
  AgentSendSubagentInputCallItem,
  AgentSession,
  AgentSessionAssistantMessage,
  AgentSessionCreatedEvent,
  AgentSessionDeleted,
  AgentSessionEnvironmentConnectedEvent,
  AgentSessionEnvironmentDisconnectedEvent,
  AgentSessionEnvironmentFailedEvent,
  AgentSessionEnvironmentPendingEvent,
  AgentSessionEnvironmentReadyEvent,
  AgentSessionEnvironmentState,
  AgentSessionErrorEvent,
  AgentSessionEvent,
  AgentSessionFailedEvent,
  AgentSessionIdleEvent,
  AgentSessionInProgressEvent,
  AgentSessionInputMessageParam,
  AgentSessionInputParam,
  AgentSessionItem,
  AgentSessionMessage,
  AgentSessionMessageContent,
  AgentSessionRequiresActionEvent,
  AgentSessionSubagentActiveEvent,
  AgentSessionSubagentClosedEvent,
  AgentSessionSubagentCreatedEvent,
  AgentSessionTurnCancelledEvent,
  AgentSessionTurnCompletedEvent,
  AgentSessionTurnContentPartAddedEvent,
  AgentSessionTurnContentPartDoneEvent,
  AgentSessionTurnCreatedEvent,
  AgentSessionTurnFailedEvent,
  AgentSessionTurnInProgressEvent,
  AgentSessionTurnItemAddedEvent,
  AgentSessionTurnItemDoneEvent,
  AgentSessionTurnOutputTextDeltaEvent,
  AgentSessionTurnOutputTextDoneEvent,
  AgentSessionTurnReasoningSummaryPartAddedEvent,
  AgentSessionTurnReasoningSummaryPartDoneEvent,
  AgentSessionTurnReasoningSummaryTextDeltaEvent,
  AgentSessionTurnReasoningSummaryTextDoneEvent,
  AgentText,
  AgentTextParam,
  AgentTool,
  AgentToolParam,
  AgentUpdateParams,
  AgentWaitForSubagentsCallItem,
  AgentWebSearchCallItem,
  Agents,
  AgentsPage,
  Environment,
  EnvironmentParam,
  HostedEnvironmentFile,
  HostedEnvironmentFileID,
  HostedEnvironmentFileParam,
  HostedPlugin,
  HostedPluginParam,
  HostedSkill,
  HostedSkillParam,
  HostedSkillReference,
  InlineCapabilitySourceParam,
  InputContent,
  InputContentParam,
  McpTransport,
  McpTransportParam,
  MultiAgentConfig,
  MultiAgentConfigParam,
  OutputText,
  PersistedAgentTool,
  PersistedAgentToolParam,
  PersistedMcpTransport,
  PersistedMcpTransportParam,
  SessionError,
  SessionTurnError,
  SetupCommandParam,
  Subagent,
  SummaryText,
  TextFormat,
  TextFormatParam,
  TokenUsage,
  WebSearchAction,
} from './agents/agents';
import * as ChatKitAPI from './chatkit/chatkit';
import { ChatKit, ChatKitWorkflow } from './chatkit/chatkit';
import * as ResponsesAPI from './responses/responses';
import {
  BetaApplyPatchTool,
  BetaCompactedResponse,
  BetaComputerAction,
  BetaComputerActionList,
  BetaComputerTool,
  BetaComputerUsePreviewTool,
  BetaContainerAuto,
  BetaContainerNetworkPolicyAllowlist,
  BetaContainerNetworkPolicyDisabled,
  BetaContainerNetworkPolicyDomainSecret,
  BetaContainerReference,
  BetaCustomTool,
  BetaEasyInputMessage,
  BetaFileSearchTool,
  BetaFunctionShellTool,
  BetaFunctionTool,
  BetaImageDetail,
  BetaInlineSkill,
  BetaInlineSkillSource,
  BetaLocalEnvironment,
  BetaLocalSkill,
  BetaMcpToolCallError,
  BetaNamespaceTool,
  BetaResponse,
  BetaResponseApplyPatchToolCall,
  BetaResponseApplyPatchToolCallOutput,
  BetaResponseAudioDeltaEvent,
  BetaResponseAudioDoneEvent,
  BetaResponseAudioTranscriptDeltaEvent,
  BetaResponseAudioTranscriptDoneEvent,
  BetaResponseCodeInterpreterCallCodeDeltaEvent,
  BetaResponseCodeInterpreterCallCodeDoneEvent,
  BetaResponseCodeInterpreterCallCompletedEvent,
  BetaResponseCodeInterpreterCallInProgressEvent,
  BetaResponseCodeInterpreterCallInterpretingEvent,
  BetaResponseCodeInterpreterToolCall,
  BetaResponseCompactionItem,
  BetaResponseCompactionItemParam,
  BetaResponseCompletedEvent,
  BetaResponseComputerToolCall,
  BetaResponseComputerToolCallOutputItem,
  BetaResponseComputerToolCallOutputScreenshot,
  BetaResponseConfigurationUpdateItem,
  BetaResponseConfigurationUpdateItemParam,
  BetaResponseContainerReference,
  BetaResponseContent,
  BetaResponseContentPartAddedEvent,
  BetaResponseContentPartDoneEvent,
  BetaResponseConversationParam,
  BetaResponseCreatedEvent,
  BetaResponseCustomToolCall,
  BetaResponseCustomToolCallInputDeltaEvent,
  BetaResponseCustomToolCallInputDoneEvent,
  BetaResponseCustomToolCallItem,
  BetaResponseCustomToolCallOutput,
  BetaResponseCustomToolCallOutputItem,
  BetaResponseError,
  BetaResponseErrorEvent,
  BetaResponseFailedEvent,
  BetaResponseFileSearchCallCompletedEvent,
  BetaResponseFileSearchCallInProgressEvent,
  BetaResponseFileSearchCallSearchingEvent,
  BetaResponseFileSearchToolCall,
  BetaResponseFormatTextConfig,
  BetaResponseFormatTextJSONSchemaConfig,
  BetaResponseFunctionCallArgumentsDeltaEvent,
  BetaResponseFunctionCallArgumentsDoneEvent,
  BetaResponseFunctionCallOutputItem,
  BetaResponseFunctionCallOutputItemList,
  BetaResponseFunctionShellCallOutputContent,
  BetaResponseFunctionShellToolCall,
  BetaResponseFunctionShellToolCallOutput,
  BetaResponseFunctionToolCall,
  BetaResponseFunctionToolCallItem,
  BetaResponseFunctionToolCallOutputItem,
  BetaResponseFunctionWebSearch,
  BetaResponseImageGenCallCompletedEvent,
  BetaResponseImageGenCallGeneratingEvent,
  BetaResponseImageGenCallInProgressEvent,
  BetaResponseImageGenCallPartialImageEvent,
  BetaResponseInProgressEvent,
  BetaResponseIncludable,
  BetaResponseIncompleteEvent,
  BetaResponseInjectCreatedEvent,
  BetaResponseInjectEvent,
  BetaResponseInjectFailedEvent,
  BetaResponseInput,
  BetaResponseInputAudio,
  BetaResponseInputContent,
  BetaResponseInputFile,
  BetaResponseInputFileContent,
  BetaResponseInputImage,
  BetaResponseInputImageContent,
  BetaResponseInputItem,
  BetaResponseInputMessageContentList,
  BetaResponseInputMessageItem,
  BetaResponseInputText,
  BetaResponseInputTextContent,
  BetaResponseItem,
  BetaResponseLocalEnvironment,
  BetaResponseMcpCallArgumentsDeltaEvent,
  BetaResponseMcpCallArgumentsDoneEvent,
  BetaResponseMcpCallCompletedEvent,
  BetaResponseMcpCallFailedEvent,
  BetaResponseMcpCallInProgressEvent,
  BetaResponseMcpListToolsCompletedEvent,
  BetaResponseMcpListToolsFailedEvent,
  BetaResponseMcpListToolsInProgressEvent,
  BetaResponseOutputAudio,
  BetaResponseOutputItem,
  BetaResponseOutputItemAddedEvent,
  BetaResponseOutputItemDoneEvent,
  BetaResponseOutputMessage,
  BetaResponseOutputRefusal,
  BetaResponseOutputText,
  BetaResponseOutputTextAnnotationAddedEvent,
  BetaResponsePrompt,
  BetaResponseQueuedEvent,
  BetaResponseReasoningItem,
  BetaResponseReasoningSummaryPartAddedEvent,
  BetaResponseReasoningSummaryPartDoneEvent,
  BetaResponseReasoningSummaryTextDeltaEvent,
  BetaResponseReasoningSummaryTextDoneEvent,
  BetaResponseReasoningTextDeltaEvent,
  BetaResponseReasoningTextDoneEvent,
  BetaResponseRefusalDeltaEvent,
  BetaResponseRefusalDoneEvent,
  BetaResponseShellCallCommandAddedEvent,
  BetaResponseShellCallCommandDeltaEvent,
  BetaResponseShellCallCommandDoneEvent,
  BetaResponseShellCallOutputContentDeltaEvent,
  BetaResponseShellCallOutputContentDoneEvent,
  BetaResponseStatus,
  BetaResponseSteerAcceptedEvent,
  BetaResponseSteerErrorCode,
  BetaResponseSteerEvent,
  BetaResponseSteerFailedEvent,
  BetaResponseSteerInput,
  BetaResponseSteerInputContent,
  BetaResponseSteerPendingEvent,
  BetaResponseSteerPendingReason,
  BetaResponseSteerRequiredInput,
  BetaResponseStreamEvent,
  BetaResponseTextConfig,
  BetaResponseTextDeltaEvent,
  BetaResponseTextDoneEvent,
  BetaResponseToolSearchCall,
  BetaResponseToolSearchOutputItem,
  BetaResponseToolSearchOutputItemParam,
  BetaResponseUsage,
  BetaResponseWebSearchCallCompletedEvent,
  BetaResponseWebSearchCallInProgressEvent,
  BetaResponseWebSearchCallSearchingEvent,
  BetaResponsesClientEvent,
  BetaResponsesServerEvent,
  BetaServiceTier,
  BetaSkillReference,
  BetaTool,
  BetaToolChoiceAllowed,
  BetaToolChoiceApplyPatch,
  BetaToolChoiceCustom,
  BetaToolChoiceFunction,
  BetaToolChoiceMcp,
  BetaToolChoiceOptions,
  BetaToolChoiceShell,
  BetaToolChoiceTypes,
  BetaToolSearchTool,
  BetaWebSearchPreviewTool,
  BetaWebSearchTool,
  ResponseCancelParams,
  ResponseCompactParams,
  ResponseCreateParams,
  ResponseCreateParamsNonStreaming,
  ResponseCreateParamsStreaming,
  ResponseDeleteParams,
  ResponseRetrieveParams,
  ResponseRetrieveParamsNonStreaming,
  ResponseRetrieveParamsStreaming,
  Responses,
} from './responses/responses';
import * as ThreadsAPI from './threads/threads';
import {
  AssistantResponseFormatOption,
  AssistantToolChoice,
  AssistantToolChoiceFunction,
  AssistantToolChoiceOption,
  Thread,
  ThreadCreateAndRunParams,
  ThreadCreateAndRunParamsNonStreaming,
  ThreadCreateAndRunParamsStreaming,
  ThreadCreateAndRunPollParams,
  ThreadCreateAndRunStreamParams,
  ThreadCreateParams,
  ThreadDeleted,
  ThreadUpdateParams,
  Threads,
} from './threads/threads';

export class Beta extends APIResource {
  realtime: RealtimeAPI.Realtime = new RealtimeAPI.Realtime(this._client);
  agents: AgentsAPI.Agents = new AgentsAPI.Agents(this._client);
  responses: ResponsesAPI.Responses = new ResponsesAPI.Responses(this._client);
  chatkit: ChatKitAPI.ChatKit = new ChatKitAPI.ChatKit(this._client);
  assistants: AssistantsAPI.Assistants = new AssistantsAPI.Assistants(this._client);
  threads: ThreadsAPI.Threads = new ThreadsAPI.Threads(this._client);
}

Beta.Realtime = Realtime;
Beta.Agents = Agents;
Beta.Responses = Responses;
Beta.ChatKit = ChatKit;
Beta.Assistants = Assistants;
Beta.Threads = Threads;

export declare namespace Beta {
  export {
    Realtime as Realtime,
    type ConversationCreatedEvent as ConversationCreatedEvent,
    type ConversationItem as ConversationItem,
    type ConversationItemContent as ConversationItemContent,
    type ConversationItemCreateEvent as ConversationItemCreateEvent,
    type ConversationItemCreatedEvent as ConversationItemCreatedEvent,
    type ConversationItemDeleteEvent as ConversationItemDeleteEvent,
    type ConversationItemDeletedEvent as ConversationItemDeletedEvent,
    type ConversationItemInputAudioTranscriptionCompletedEvent as ConversationItemInputAudioTranscriptionCompletedEvent,
    type ConversationItemInputAudioTranscriptionDeltaEvent as ConversationItemInputAudioTranscriptionDeltaEvent,
    type ConversationItemInputAudioTranscriptionFailedEvent as ConversationItemInputAudioTranscriptionFailedEvent,
    type ConversationItemRetrieveEvent as ConversationItemRetrieveEvent,
    type ConversationItemTruncateEvent as ConversationItemTruncateEvent,
    type ConversationItemTruncatedEvent as ConversationItemTruncatedEvent,
    type ConversationItemWithReference as ConversationItemWithReference,
    type ErrorEvent as ErrorEvent,
    type InputAudioBufferAppendEvent as InputAudioBufferAppendEvent,
    type InputAudioBufferClearEvent as InputAudioBufferClearEvent,
    type InputAudioBufferClearedEvent as InputAudioBufferClearedEvent,
    type InputAudioBufferCommitEvent as InputAudioBufferCommitEvent,
    type InputAudioBufferCommittedEvent as InputAudioBufferCommittedEvent,
    type InputAudioBufferSpeechStartedEvent as InputAudioBufferSpeechStartedEvent,
    type InputAudioBufferSpeechStoppedEvent as InputAudioBufferSpeechStoppedEvent,
    type RateLimitsUpdatedEvent as RateLimitsUpdatedEvent,
    type RealtimeClientEvent as RealtimeClientEvent,
    type RealtimeResponse as RealtimeResponse,
    type RealtimeResponseStatus as RealtimeResponseStatus,
    type RealtimeResponseUsage as RealtimeResponseUsage,
    type RealtimeServerEvent as RealtimeServerEvent,
    type ResponseAudioDeltaEvent as ResponseAudioDeltaEvent,
    type ResponseAudioDoneEvent as ResponseAudioDoneEvent,
    type ResponseAudioTranscriptDeltaEvent as ResponseAudioTranscriptDeltaEvent,
    type ResponseAudioTranscriptDoneEvent as ResponseAudioTranscriptDoneEvent,
    type ResponseCancelEvent as ResponseCancelEvent,
    type ResponseContentPartAddedEvent as ResponseContentPartAddedEvent,
    type ResponseContentPartDoneEvent as ResponseContentPartDoneEvent,
    type ResponseCreateEvent as ResponseCreateEvent,
    type ResponseCreatedEvent as ResponseCreatedEvent,
    type ResponseDoneEvent as ResponseDoneEvent,
    type ResponseFunctionCallArgumentsDeltaEvent as ResponseFunctionCallArgumentsDeltaEvent,
    type ResponseFunctionCallArgumentsDoneEvent as ResponseFunctionCallArgumentsDoneEvent,
    type ResponseOutputItemAddedEvent as ResponseOutputItemAddedEvent,
    type ResponseOutputItemDoneEvent as ResponseOutputItemDoneEvent,
    type ResponseTextDeltaEvent as ResponseTextDeltaEvent,
    type ResponseTextDoneEvent as ResponseTextDoneEvent,
    type SessionCreatedEvent as SessionCreatedEvent,
    type SessionUpdateEvent as SessionUpdateEvent,
    type SessionUpdatedEvent as SessionUpdatedEvent,
    type TranscriptionSessionUpdate as TranscriptionSessionUpdate,
    type TranscriptionSessionUpdatedEvent as TranscriptionSessionUpdatedEvent,
    Agents as Agents,
    type Agent as Agent,
    type AgentCloseSubagentCallItem as AgentCloseSubagentCallItem,
    type AgentCommandExecutionItem as AgentCommandExecutionItem,
    type AgentContent as AgentContent,
    type AgentCreateSubagentCallItem as AgentCreateSubagentCallItem,
    type AgentDeleted as AgentDeleted,
    type AgentFunctionCallItem as AgentFunctionCallItem,
    type AgentFunctionCallOutput as AgentFunctionCallOutput,
    type AgentFunctionCallOutputParam as AgentFunctionCallOutputParam,
    type AgentFunctionCallStatus as AgentFunctionCallStatus,
    type AgentInterruptSubagentCallItem as AgentInterruptSubagentCallItem,
    type AgentMcpCallItem as AgentMcpCallItem,
    type AgentOutputCommandExecutionOutputDeltaEvent as AgentOutputCommandExecutionOutputDeltaEvent,
    type AgentOutputItem as AgentOutputItem,
    type AgentOutputItemStatus as AgentOutputItemStatus,
    type AgentReasoning as AgentReasoning,
    type AgentReasoningItem as AgentReasoningItem,
    type AgentReasoningParam as AgentReasoningParam,
    type AgentResumeSubagentCallItem as AgentResumeSubagentCallItem,
    type AgentSendSubagentInputCallItem as AgentSendSubagentInputCallItem,
    type AgentSession as AgentSession,
    type AgentSessionAssistantMessage as AgentSessionAssistantMessage,
    type AgentSessionCreatedEvent as AgentSessionCreatedEvent,
    type AgentSessionDeleted as AgentSessionDeleted,
    type AgentSessionEnvironmentConnectedEvent as AgentSessionEnvironmentConnectedEvent,
    type AgentSessionEnvironmentDisconnectedEvent as AgentSessionEnvironmentDisconnectedEvent,
    type AgentSessionEnvironmentFailedEvent as AgentSessionEnvironmentFailedEvent,
    type AgentSessionEnvironmentPendingEvent as AgentSessionEnvironmentPendingEvent,
    type AgentSessionEnvironmentReadyEvent as AgentSessionEnvironmentReadyEvent,
    type AgentSessionEnvironmentState as AgentSessionEnvironmentState,
    type AgentSessionErrorEvent as AgentSessionErrorEvent,
    type AgentSessionEvent as AgentSessionEvent,
    type AgentSessionFailedEvent as AgentSessionFailedEvent,
    type AgentSessionIdleEvent as AgentSessionIdleEvent,
    type AgentSessionInProgressEvent as AgentSessionInProgressEvent,
    type AgentSessionInputMessageParam as AgentSessionInputMessageParam,
    type AgentSessionInputParam as AgentSessionInputParam,
    type AgentSessionItem as AgentSessionItem,
    type AgentSessionMessage as AgentSessionMessage,
    type AgentSessionMessageContent as AgentSessionMessageContent,
    type AgentSessionRequiresActionEvent as AgentSessionRequiresActionEvent,
    type AgentSessionSubagentActiveEvent as AgentSessionSubagentActiveEvent,
    type AgentSessionSubagentClosedEvent as AgentSessionSubagentClosedEvent,
    type AgentSessionSubagentCreatedEvent as AgentSessionSubagentCreatedEvent,
    type AgentSessionTurnCancelledEvent as AgentSessionTurnCancelledEvent,
    type AgentSessionTurnCompletedEvent as AgentSessionTurnCompletedEvent,
    type AgentSessionTurnContentPartAddedEvent as AgentSessionTurnContentPartAddedEvent,
    type AgentSessionTurnContentPartDoneEvent as AgentSessionTurnContentPartDoneEvent,
    type AgentSessionTurnCreatedEvent as AgentSessionTurnCreatedEvent,
    type AgentSessionTurnFailedEvent as AgentSessionTurnFailedEvent,
    type AgentSessionTurnInProgressEvent as AgentSessionTurnInProgressEvent,
    type AgentSessionTurnItemAddedEvent as AgentSessionTurnItemAddedEvent,
    type AgentSessionTurnItemDoneEvent as AgentSessionTurnItemDoneEvent,
    type AgentSessionTurnOutputTextDeltaEvent as AgentSessionTurnOutputTextDeltaEvent,
    type AgentSessionTurnOutputTextDoneEvent as AgentSessionTurnOutputTextDoneEvent,
    type AgentSessionTurnReasoningSummaryPartAddedEvent as AgentSessionTurnReasoningSummaryPartAddedEvent,
    type AgentSessionTurnReasoningSummaryPartDoneEvent as AgentSessionTurnReasoningSummaryPartDoneEvent,
    type AgentSessionTurnReasoningSummaryTextDeltaEvent as AgentSessionTurnReasoningSummaryTextDeltaEvent,
    type AgentSessionTurnReasoningSummaryTextDoneEvent as AgentSessionTurnReasoningSummaryTextDoneEvent,
    type AgentText as AgentText,
    type AgentTextParam as AgentTextParam,
    type AgentTool as AgentTool,
    type AgentToolParam as AgentToolParam,
    type AgentWaitForSubagentsCallItem as AgentWaitForSubagentsCallItem,
    type AgentWebSearchCallItem as AgentWebSearchCallItem,
    type Environment as Environment,
    type EnvironmentParam as EnvironmentParam,
    type HostedEnvironmentFile as HostedEnvironmentFile,
    type HostedEnvironmentFileID as HostedEnvironmentFileID,
    type HostedEnvironmentFileParam as HostedEnvironmentFileParam,
    type HostedPlugin as HostedPlugin,
    type HostedPluginParam as HostedPluginParam,
    type HostedSkill as HostedSkill,
    type HostedSkillParam as HostedSkillParam,
    type HostedSkillReference as HostedSkillReference,
    type InlineCapabilitySourceParam as InlineCapabilitySourceParam,
    type InputContent as InputContent,
    type InputContentParam as InputContentParam,
    type McpTransport as McpTransport,
    type McpTransportParam as McpTransportParam,
    type MultiAgentConfig as MultiAgentConfig,
    type MultiAgentConfigParam as MultiAgentConfigParam,
    type OutputText as OutputText,
    type PersistedAgentTool as PersistedAgentTool,
    type PersistedAgentToolParam as PersistedAgentToolParam,
    type PersistedMcpTransport as PersistedMcpTransport,
    type PersistedMcpTransportParam as PersistedMcpTransportParam,
    type SessionError as SessionError,
    type SessionTurnError as SessionTurnError,
    type SetupCommandParam as SetupCommandParam,
    type Subagent as Subagent,
    type SummaryText as SummaryText,
    type TextFormat as TextFormat,
    type TextFormatParam as TextFormatParam,
    type TokenUsage as TokenUsage,
    type WebSearchAction as WebSearchAction,
    type AgentsPage as AgentsPage,
    type AgentCreateParams as AgentCreateParams,
    type AgentUpdateParams as AgentUpdateParams,
    type AgentListParams as AgentListParams,
  };

  export {
    Responses as Responses,
    type BetaApplyPatchTool as BetaApplyPatchTool,
    type BetaCompactedResponse as BetaCompactedResponse,
    type BetaComputerAction as BetaComputerAction,
    type BetaComputerActionList as BetaComputerActionList,
    type BetaComputerTool as BetaComputerTool,
    type BetaComputerUsePreviewTool as BetaComputerUsePreviewTool,
    type BetaContainerAuto as BetaContainerAuto,
    type BetaContainerNetworkPolicyAllowlist as BetaContainerNetworkPolicyAllowlist,
    type BetaContainerNetworkPolicyDisabled as BetaContainerNetworkPolicyDisabled,
    type BetaContainerNetworkPolicyDomainSecret as BetaContainerNetworkPolicyDomainSecret,
    type BetaContainerReference as BetaContainerReference,
    type BetaCustomTool as BetaCustomTool,
    type BetaEasyInputMessage as BetaEasyInputMessage,
    type BetaFileSearchTool as BetaFileSearchTool,
    type BetaFunctionShellTool as BetaFunctionShellTool,
    type BetaFunctionTool as BetaFunctionTool,
    type BetaImageDetail as BetaImageDetail,
    type BetaInlineSkill as BetaInlineSkill,
    type BetaInlineSkillSource as BetaInlineSkillSource,
    type BetaLocalEnvironment as BetaLocalEnvironment,
    type BetaLocalSkill as BetaLocalSkill,
    type BetaMcpToolCallError as BetaMcpToolCallError,
    type BetaNamespaceTool as BetaNamespaceTool,
    type BetaResponse as BetaResponse,
    type BetaResponseApplyPatchToolCall as BetaResponseApplyPatchToolCall,
    type BetaResponseApplyPatchToolCallOutput as BetaResponseApplyPatchToolCallOutput,
    type BetaResponseAudioDeltaEvent as BetaResponseAudioDeltaEvent,
    type BetaResponseAudioDoneEvent as BetaResponseAudioDoneEvent,
    type BetaResponseAudioTranscriptDeltaEvent as BetaResponseAudioTranscriptDeltaEvent,
    type BetaResponseAudioTranscriptDoneEvent as BetaResponseAudioTranscriptDoneEvent,
    type BetaResponseCodeInterpreterCallCodeDeltaEvent as BetaResponseCodeInterpreterCallCodeDeltaEvent,
    type BetaResponseCodeInterpreterCallCodeDoneEvent as BetaResponseCodeInterpreterCallCodeDoneEvent,
    type BetaResponseCodeInterpreterCallCompletedEvent as BetaResponseCodeInterpreterCallCompletedEvent,
    type BetaResponseCodeInterpreterCallInProgressEvent as BetaResponseCodeInterpreterCallInProgressEvent,
    type BetaResponseCodeInterpreterCallInterpretingEvent as BetaResponseCodeInterpreterCallInterpretingEvent,
    type BetaResponseCodeInterpreterToolCall as BetaResponseCodeInterpreterToolCall,
    type BetaResponseCompactionItem as BetaResponseCompactionItem,
    type BetaResponseCompactionItemParam as BetaResponseCompactionItemParam,
    type BetaResponseCompletedEvent as BetaResponseCompletedEvent,
    type BetaResponseComputerToolCall as BetaResponseComputerToolCall,
    type BetaResponseComputerToolCallOutputItem as BetaResponseComputerToolCallOutputItem,
    type BetaResponseComputerToolCallOutputScreenshot as BetaResponseComputerToolCallOutputScreenshot,
    type BetaResponseConfigurationUpdateItem as BetaResponseConfigurationUpdateItem,
    type BetaResponseConfigurationUpdateItemParam as BetaResponseConfigurationUpdateItemParam,
    type BetaResponseContainerReference as BetaResponseContainerReference,
    type BetaResponseContent as BetaResponseContent,
    type BetaResponseContentPartAddedEvent as BetaResponseContentPartAddedEvent,
    type BetaResponseContentPartDoneEvent as BetaResponseContentPartDoneEvent,
    type BetaResponseConversationParam as BetaResponseConversationParam,
    type BetaResponseCreatedEvent as BetaResponseCreatedEvent,
    type BetaResponseCustomToolCall as BetaResponseCustomToolCall,
    type BetaResponseCustomToolCallInputDeltaEvent as BetaResponseCustomToolCallInputDeltaEvent,
    type BetaResponseCustomToolCallInputDoneEvent as BetaResponseCustomToolCallInputDoneEvent,
    type BetaResponseCustomToolCallItem as BetaResponseCustomToolCallItem,
    type BetaResponseCustomToolCallOutput as BetaResponseCustomToolCallOutput,
    type BetaResponseCustomToolCallOutputItem as BetaResponseCustomToolCallOutputItem,
    type BetaResponseError as BetaResponseError,
    type BetaResponseErrorEvent as BetaResponseErrorEvent,
    type BetaResponseFailedEvent as BetaResponseFailedEvent,
    type BetaResponseFileSearchCallCompletedEvent as BetaResponseFileSearchCallCompletedEvent,
    type BetaResponseFileSearchCallInProgressEvent as BetaResponseFileSearchCallInProgressEvent,
    type BetaResponseFileSearchCallSearchingEvent as BetaResponseFileSearchCallSearchingEvent,
    type BetaResponseFileSearchToolCall as BetaResponseFileSearchToolCall,
    type BetaResponseFormatTextConfig as BetaResponseFormatTextConfig,
    type BetaResponseFormatTextJSONSchemaConfig as BetaResponseFormatTextJSONSchemaConfig,
    type BetaResponseFunctionCallArgumentsDeltaEvent as BetaResponseFunctionCallArgumentsDeltaEvent,
    type BetaResponseFunctionCallArgumentsDoneEvent as BetaResponseFunctionCallArgumentsDoneEvent,
    type BetaResponseFunctionCallOutputItem as BetaResponseFunctionCallOutputItem,
    type BetaResponseFunctionCallOutputItemList as BetaResponseFunctionCallOutputItemList,
    type BetaResponseFunctionShellCallOutputContent as BetaResponseFunctionShellCallOutputContent,
    type BetaResponseFunctionShellToolCall as BetaResponseFunctionShellToolCall,
    type BetaResponseFunctionShellToolCallOutput as BetaResponseFunctionShellToolCallOutput,
    type BetaResponseFunctionToolCall as BetaResponseFunctionToolCall,
    type BetaResponseFunctionToolCallItem as BetaResponseFunctionToolCallItem,
    type BetaResponseFunctionToolCallOutputItem as BetaResponseFunctionToolCallOutputItem,
    type BetaResponseFunctionWebSearch as BetaResponseFunctionWebSearch,
    type BetaResponseImageGenCallCompletedEvent as BetaResponseImageGenCallCompletedEvent,
    type BetaResponseImageGenCallGeneratingEvent as BetaResponseImageGenCallGeneratingEvent,
    type BetaResponseImageGenCallInProgressEvent as BetaResponseImageGenCallInProgressEvent,
    type BetaResponseImageGenCallPartialImageEvent as BetaResponseImageGenCallPartialImageEvent,
    type BetaResponseInProgressEvent as BetaResponseInProgressEvent,
    type BetaResponseIncludable as BetaResponseIncludable,
    type BetaResponseIncompleteEvent as BetaResponseIncompleteEvent,
    type BetaResponseInjectCreatedEvent as BetaResponseInjectCreatedEvent,
    type BetaResponseInjectEvent as BetaResponseInjectEvent,
    type BetaResponseInjectFailedEvent as BetaResponseInjectFailedEvent,
    type BetaResponseInput as BetaResponseInput,
    type BetaResponseInputAudio as BetaResponseInputAudio,
    type BetaResponseInputContent as BetaResponseInputContent,
    type BetaResponseInputFile as BetaResponseInputFile,
    type BetaResponseInputFileContent as BetaResponseInputFileContent,
    type BetaResponseInputImage as BetaResponseInputImage,
    type BetaResponseInputImageContent as BetaResponseInputImageContent,
    type BetaResponseInputItem as BetaResponseInputItem,
    type BetaResponseInputMessageContentList as BetaResponseInputMessageContentList,
    type BetaResponseInputMessageItem as BetaResponseInputMessageItem,
    type BetaResponseInputText as BetaResponseInputText,
    type BetaResponseInputTextContent as BetaResponseInputTextContent,
    type BetaResponseItem as BetaResponseItem,
    type BetaResponseLocalEnvironment as BetaResponseLocalEnvironment,
    type BetaResponseMcpCallArgumentsDeltaEvent as BetaResponseMcpCallArgumentsDeltaEvent,
    type BetaResponseMcpCallArgumentsDoneEvent as BetaResponseMcpCallArgumentsDoneEvent,
    type BetaResponseMcpCallCompletedEvent as BetaResponseMcpCallCompletedEvent,
    type BetaResponseMcpCallFailedEvent as BetaResponseMcpCallFailedEvent,
    type BetaResponseMcpCallInProgressEvent as BetaResponseMcpCallInProgressEvent,
    type BetaResponseMcpListToolsCompletedEvent as BetaResponseMcpListToolsCompletedEvent,
    type BetaResponseMcpListToolsFailedEvent as BetaResponseMcpListToolsFailedEvent,
    type BetaResponseMcpListToolsInProgressEvent as BetaResponseMcpListToolsInProgressEvent,
    type BetaResponseOutputAudio as BetaResponseOutputAudio,
    type BetaResponseOutputItem as BetaResponseOutputItem,
    type BetaResponseOutputItemAddedEvent as BetaResponseOutputItemAddedEvent,
    type BetaResponseOutputItemDoneEvent as BetaResponseOutputItemDoneEvent,
    type BetaResponseOutputMessage as BetaResponseOutputMessage,
    type BetaResponseOutputRefusal as BetaResponseOutputRefusal,
    type BetaResponseOutputText as BetaResponseOutputText,
    type BetaResponseOutputTextAnnotationAddedEvent as BetaResponseOutputTextAnnotationAddedEvent,
    type BetaResponsePrompt as BetaResponsePrompt,
    type BetaResponseQueuedEvent as BetaResponseQueuedEvent,
    type BetaResponseReasoningItem as BetaResponseReasoningItem,
    type BetaResponseReasoningSummaryPartAddedEvent as BetaResponseReasoningSummaryPartAddedEvent,
    type BetaResponseReasoningSummaryPartDoneEvent as BetaResponseReasoningSummaryPartDoneEvent,
    type BetaResponseReasoningSummaryTextDeltaEvent as BetaResponseReasoningSummaryTextDeltaEvent,
    type BetaResponseReasoningSummaryTextDoneEvent as BetaResponseReasoningSummaryTextDoneEvent,
    type BetaResponseReasoningTextDeltaEvent as BetaResponseReasoningTextDeltaEvent,
    type BetaResponseReasoningTextDoneEvent as BetaResponseReasoningTextDoneEvent,
    type BetaResponseRefusalDeltaEvent as BetaResponseRefusalDeltaEvent,
    type BetaResponseRefusalDoneEvent as BetaResponseRefusalDoneEvent,
    type BetaResponseShellCallCommandAddedEvent as BetaResponseShellCallCommandAddedEvent,
    type BetaResponseShellCallCommandDeltaEvent as BetaResponseShellCallCommandDeltaEvent,
    type BetaResponseShellCallCommandDoneEvent as BetaResponseShellCallCommandDoneEvent,
    type BetaResponseShellCallOutputContentDeltaEvent as BetaResponseShellCallOutputContentDeltaEvent,
    type BetaResponseShellCallOutputContentDoneEvent as BetaResponseShellCallOutputContentDoneEvent,
    type BetaResponseStatus as BetaResponseStatus,
    type BetaResponseSteerAcceptedEvent as BetaResponseSteerAcceptedEvent,
    type BetaResponseSteerErrorCode as BetaResponseSteerErrorCode,
    type BetaResponseSteerEvent as BetaResponseSteerEvent,
    type BetaResponseSteerFailedEvent as BetaResponseSteerFailedEvent,
    type BetaResponseSteerInput as BetaResponseSteerInput,
    type BetaResponseSteerInputContent as BetaResponseSteerInputContent,
    type BetaResponseSteerPendingEvent as BetaResponseSteerPendingEvent,
    type BetaResponseSteerPendingReason as BetaResponseSteerPendingReason,
    type BetaResponseSteerRequiredInput as BetaResponseSteerRequiredInput,
    type BetaResponseStreamEvent as BetaResponseStreamEvent,
    type BetaResponseTextConfig as BetaResponseTextConfig,
    type BetaResponseTextDeltaEvent as BetaResponseTextDeltaEvent,
    type BetaResponseTextDoneEvent as BetaResponseTextDoneEvent,
    type BetaResponseToolSearchCall as BetaResponseToolSearchCall,
    type BetaResponseToolSearchOutputItem as BetaResponseToolSearchOutputItem,
    type BetaResponseToolSearchOutputItemParam as BetaResponseToolSearchOutputItemParam,
    type BetaResponseUsage as BetaResponseUsage,
    type BetaResponseWebSearchCallCompletedEvent as BetaResponseWebSearchCallCompletedEvent,
    type BetaResponseWebSearchCallInProgressEvent as BetaResponseWebSearchCallInProgressEvent,
    type BetaResponseWebSearchCallSearchingEvent as BetaResponseWebSearchCallSearchingEvent,
    type BetaResponsesClientEvent as BetaResponsesClientEvent,
    type BetaResponsesServerEvent as BetaResponsesServerEvent,
    type BetaServiceTier as BetaServiceTier,
    type BetaSkillReference as BetaSkillReference,
    type BetaTool as BetaTool,
    type BetaToolChoiceAllowed as BetaToolChoiceAllowed,
    type BetaToolChoiceApplyPatch as BetaToolChoiceApplyPatch,
    type BetaToolChoiceCustom as BetaToolChoiceCustom,
    type BetaToolChoiceFunction as BetaToolChoiceFunction,
    type BetaToolChoiceMcp as BetaToolChoiceMcp,
    type BetaToolChoiceOptions as BetaToolChoiceOptions,
    type BetaToolChoiceShell as BetaToolChoiceShell,
    type BetaToolChoiceTypes as BetaToolChoiceTypes,
    type BetaToolSearchTool as BetaToolSearchTool,
    type BetaWebSearchPreviewTool as BetaWebSearchPreviewTool,
    type BetaWebSearchTool as BetaWebSearchTool,
    type ResponseCreateParams as ResponseCreateParams,
    type ResponseCreateParamsNonStreaming as ResponseCreateParamsNonStreaming,
    type ResponseCreateParamsStreaming as ResponseCreateParamsStreaming,
    type ResponseRetrieveParams as ResponseRetrieveParams,
    type ResponseRetrieveParamsNonStreaming as ResponseRetrieveParamsNonStreaming,
    type ResponseRetrieveParamsStreaming as ResponseRetrieveParamsStreaming,
    type ResponseDeleteParams as ResponseDeleteParams,
    type ResponseCancelParams as ResponseCancelParams,
    type ResponseCompactParams as ResponseCompactParams,
  };

  export { ChatKit as ChatKit, type ChatKitWorkflow as ChatKitWorkflow };

  export {
    Assistants as Assistants,
    type Assistant as Assistant,
    type AssistantDeleted as AssistantDeleted,
    type AssistantStreamEvent as AssistantStreamEvent,
    type AssistantTool as AssistantTool,
    type CodeInterpreterTool as CodeInterpreterTool,
    type FileSearchTool as FileSearchTool,
    type FunctionTool as FunctionTool,
    type MessageStreamEvent as MessageStreamEvent,
    type RunStepStreamEvent as RunStepStreamEvent,
    type RunStreamEvent as RunStreamEvent,
    type ThreadStreamEvent as ThreadStreamEvent,
    type AssistantsPage as AssistantsPage,
    type AssistantCreateParams as AssistantCreateParams,
    type AssistantUpdateParams as AssistantUpdateParams,
    type AssistantListParams as AssistantListParams,
  };

  export {
    Threads as Threads,
    type AssistantResponseFormatOption as AssistantResponseFormatOption,
    type AssistantToolChoice as AssistantToolChoice,
    type AssistantToolChoiceFunction as AssistantToolChoiceFunction,
    type AssistantToolChoiceOption as AssistantToolChoiceOption,
    type Thread as Thread,
    type ThreadDeleted as ThreadDeleted,
    type ThreadCreateParams as ThreadCreateParams,
    type ThreadUpdateParams as ThreadUpdateParams,
    type ThreadCreateAndRunParams as ThreadCreateAndRunParams,
    type ThreadCreateAndRunParamsNonStreaming as ThreadCreateAndRunParamsNonStreaming,
    type ThreadCreateAndRunParamsStreaming as ThreadCreateAndRunParamsStreaming,
    type ThreadCreateAndRunPollParams,
    type ThreadCreateAndRunStreamParams,
  };
}
