name: Create releases
on:
  schedule:
    - cron: '0 5 * * *' # every day at 5am UTC
  push:
    branches:
      - master

jobs:
  release:
    name: release
    if: github.ref == 'refs/heads/master' && github.repository == 'openai/openai-node'
    runs-on: ubuntu-latest
    environment: publish
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: stainless-api/trigger-release-please@v1
        id: release
        with:
          repo: ${{ github.event.repository.full_name }}
          stainless-api-key: ${{ secrets.STAINLESS_API_KEY }}

      - name: Set up Node
        if: ${{ steps.release.outputs.releases_created }}
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        if: ${{ steps.release.outputs.releases_created }}
        run: |
          yarn install

      - name: Publish to NPM
        if: ${{ steps.release.outputs.releases_created }}
        run: |
          bash ./bin/publish-npm
        env:
          NPM_TOKEN: ${{ secrets.OPENAI_NPM_TOKEN || secrets.NPM_TOKEN }}

      - name: Publish to JSR
        if: ${{ steps.release.outputs.releases_created }}
        run: |
          bash ./bin/publish-jsr

